
var A = [{
    "items": [{
        "tags": ["mysql", "phpmyadmin", "codemirror"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 38409618,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468682518,
        "creation_date": 1468660771,
        "body": "I created two tables from phpmyadmin like this\n\n\n\nand another one like this\n\n\n\nafter this i insert a value in the first table called &#39;customers&#39; like this:\n\n\n\nnow after that when i insert values into the &#39;orders&#39; table, phpmyadmin linter displays error like this:\n\n\n\nHowever, strangely when i click &#39;Go&#39;, the query works fine. It also works fine through the command line too. So is it a bug? or i have to write it in a different way?\n",
        "excerpt": "I created two tables from phpmyadmin like this\n\nCREATE TABLE customers (\nid int(11) NOT NULL AUTO_INCREMENT,\nname varchar(245) DEFAULT NULL,\nplace varchar(245) DEFAULT NULL,\nemail varchar(245) DEFAULT &hellip; ",
        "title": "Does phpmyadmin&#39;s linter has a bug?"
    }, {
        "tags": ["python", "arrays", "numpy"],
        "question_score": 1,
        "is_accepted": false,
        "answer_id": 38406982,
        "is_answered": false,
        "question_id": 38406638,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1468682514,
        "creation_date": 1468634139,
        "body": " will broadcast the comparison, so \n\n\n\nPrinting out the intermediate steps will be useful to understanding and working out similar tasks:\n\n\n\nIf instead you used , then everything would be .\n",
        "excerpt": "== will broadcast the comparison, so \n\nwallxy = numpy.array([[0, 1],[3, 2][4, 6]])\nz0 = numpy.array([3,2])\nz1 = numpy.array([2,3])\n\n(z0==wallxy).all(1).any()  # True\n(z1==wallxy).all(1).any()  # False &hellip; ",
        "title": "If X and Y matches element in NumPy Array"
    }],
    "name": "SWAGGGGG"
}, {
    "items": [{
        "tags": ["php", "laravel-5"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38410687,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468672266,
        "creation_date": 1468668215,
        "body": "When i tried to update illuminate like that but failed. \n\n\n\nit showed that error,\n\n\n\nplease help me.\n",
        "excerpt": " returned with an <span class=\"highlight\">error</span>\n\nInstallation failed, reverting ./composer.json to its original content.\n\n\n[<span class=\"highlight\">RuntimeException</span>]  \n<span class=\"highlight\">Error</span> Output:   \n\n\nplease help me.\n &hellip; When i tried to update illuminate like that but failed. \n\nsudo composer.phar require &quot;illuminate/html&quot;:&quot;5.0.*&quot;\n\n\nit showed that <span class=\"highlight\">error</span>,\n\nScript php artisan optimize handling the post-update-cmd event &hellip; ",
        "title": "laravel composer update fail when trying to update illuminate"
    }, {
        "tags": ["java", "spring", "maven", "jpa", "aspectj"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38200747,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468670040,
        "creation_date": 1467713576,
        "body": "I am trying aspectj with EntityManager, its giving error\n\n\n\nPOM:    \n\n\n\nDriver application:\n\n\n\nService class:\n\n\n\nAspect:\n\n\n\napplication.properties:\n\n\n\nNeed to know where am doing wrong??\n",
        "excerpt": "I am trying aspectj with EntityManager, its giving <span class=\"highlight\">error</span>\n\norg.springframework.beans.factory.BeanCreationException:\n  <span class=\"highlight\">Error</span> creating bean with name &hellip; );\n            service.save();\n\n        } catch (<span class=\"highlight\">RuntimeException</span> e) {\n            System.out.println(&quot;Caught runtime exception&quot;);\n        }\n    }\n}\n\n\nService class:\n\n@Component\npublic class Service &hellip; ",
        "title": "EntityManager with aspectj is not working"
    }, {
        "tags": ["java", "mockito"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 38406139,
        "is_answered": false,
        "question_id": 38405897,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1468624011,
        "creation_date": 1468624011,
        "body": " supports a  call that returns a list of every matching capture. You could use this to verify both messages.\n\n\n\nHowever, in the general case, this is a perfect opportunity to write a Hamcrest(-style) matcher that checks the message for you. I use Mockito&#39;s ArgumentMatcher class here, which extended Hamcrest&#39;s Matcher in Mockito 1.x but breaks that dependency in Mockito 2.0.\n\n\n\nNow you can use it in both  and  calls, wrapped with adapter :\n\n\n\nFor more about which  to use and why you need it, see: How do Mockito matchers work?\n",
        "excerpt": "(logEventArgumentCaptor.capture());\n\nassertThat(logEventArgumentCaptor.getAllValues().get(0).getMessage(),\n    containsString(&quot;<span class=\"highlight\">Error</span> response: &quot; + RESPONSE ));\nassertThat(logEventArgumentCaptor.getAllValues().get(1 &hellip;  can use it in both when and verify calls, wrapped with adapter argThat:\n\nverify(mockAppender)\n    .doAppend(argThat(isALogEventContaining(&quot;<span class=\"highlight\">Error</span> response: &quot; + RESPONSE)));\nverify(mockAppender, never &hellip; ",
        "title": "How can I use Mockito to test two different calls to the same method that returns a different response for each call?"
    }, {
        "tags": ["php"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38376474,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468614939,
        "creation_date": 1468505321,
        "body": "For a while now I have been trying to alter my ACRA backend to include issue ID&#39;s so each issue doesn&#39;t show up as a single one, but shows up as one issue with a report count. Because of that I worked out this:\n\n\n\nThis is supposed to take the stacktrace and package and convert it to an issue ID that can be used over and over for the same issue whenever it is reported. So I caused an error in my app which transmits this: \n\n\n\nIt is the exact same every time except for the time defined in front of each line.\n\nFor the problem: The exact same input every time, but it generates different ID&#39;s every time. I caused it 3 times and here are the ID&#39;s:\n\n\n\nThe stacktrace is not included the first two and last two lines of the .txt file. \n\nHow can I fix this? It is really annoying because it took ages to work out the code above and it doesn&#39;t work. \n\nTo clairify:\n\nI want the output(ID) to be the same if the stacktrace is the same, but it doesn&#39;t appear to be working.\n",
        "excerpt": "\n             || strpos($line, &quot;<span class=\"highlight\">Error</span>&quot;) !== FALSE || strpos($line, &quot;ACRA caught a&quot;) !== FALSE) {\n                $value .= $line . &quot;&lt;br /&gt;&quot;;\n            }\n        }\n    }\n    return $value;\n}\n\nfunction &hellip;  over and over for the same issue whenever it is reported. So I caused an <span class=\"highlight\">error</span> in my app which transmits this: \n\nPACKAGE_NAME = com.gamerscave.codingclicker\nAPP_VERSION_NAME = 1.1.5\nLOGCAT = 07-14 15 &hellip; ",
        "title": "Creating ID for issues based on two parameters"
    }, {
        "tags": ["websphere", "websphere-7"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 7672688,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468608401,
        "creation_date": 1317894661,
        "body": "I am having issue with a restful web service deployed on WebSphere 7. Each time I try to access a url I&#39;m getting this error message:\n\n\n\nI am suspecting my indirect lookups as the cause of the problem. I have my look up code like this\n\n\n\nApart from this, I have created my datasource and tested successfully with WebSphere. What is the evil i am doing wrong?\n\nHere is my stack trace:\n\n\n",
        "excerpt": "I am having issue with a restful web service deployed on WebSphere 7. Each time I try to access a url I&#39;m getting this <span class=\"highlight\">error</span> message:\n\n&quot;WLTC0017E: Resources rolled back due to setRollbackOnly() being &hellip; /persistence/BACPOnlineAPPPU);\n    this.utx = (UserTransaction) new InitialContext().lookup(&quot;java:comp/UserTransaction&quot;);\n    } catch (NamingException ex) {\n        throw new <span class=\"highlight\">RuntimeException</span>(ex);\n\n    }\n\n\nApart &hellip; ",
        "title": "WLTC0017E:Resources rolled back due to setRollbackOnly() being called error"
    }, {
        "tags": ["java", "intellij-idea"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 38402365,
        "is_answered": false,
        "question_id": 38401821,
        "item_type": "answer",
        "score": 2,
        "last_activity_date": 1468606368,
        "creation_date": 1468605094,
        "body": "Thanks to your edit, it&#39;s easier to explain the behavior you&#39;re seeing. IntelliJ flags Exceptions that do not subclass java.lang.RuntimeException because that is an actual compilation error. \n\nLet&#39;s look at the JavaDoc for Exception:\n\n\n  The class Exception and any subclasses that are not also subclasses of RuntimeException are checked exceptions. Checked exceptions need to be declared in a method or constructor&#39;s throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.\n\n\n... And the JavaDoc for RuntimeException:\n\n\n  RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor&#39;s throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.\n\n\nIn other words, you can throw a RuntimeException overtly in your code, and you don&#39;t necessarily have to declare it or catch it, and your compiler will be perfectly happy with that (although your API&#39;s users might not be so jolly). On the other hand, Exceptions that do not subclass RuntimeException are called &quot;checked&quot; exceptions, and must either be declared as thrown by your methods or caught and handled when they might occur, in accordance with the language&#39;s specifications.\n\n(P.S., if you didn&#39;t catch it yet, NullPointerException is a RuntimeException. Hence, it is unchecked.)\n",
        "excerpt": "Thanks to your edit, it&#39;s easier to explain the behavior you&#39;re seeing. IntelliJ flags Exceptions that do not subclass java.lang.RuntimeException because that is an actual compilation <span class=\"highlight\">error</span>. \n\nLet&#39;s &hellip;  look at the JavaDoc for Exception:\n\n\n  The class Exception and any subclasses that are not also subclasses of <span class=\"highlight\">RuntimeException</span> are checked exceptions. Checked exceptions need to be declared &hellip; ",
        "title": "IntelliJ IDEA doesn&#39;t highlight the code which throws an exception - how to turn it on?"
    }, {
        "tags": ["java", "generics", "type-safety"],
        "question_score": 4,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 38289465,
        "item_type": "question",
        "score": 4,
        "last_activity_date": 1468604938,
        "creation_date": 1468134033,
        "body": "I&#39;m trying to write a collection that&#39;s 100% type safe. I have it all working properly the only issue I&#39;m struggling with is this.\n\n\n\nOutput without the run-time error\n\n\n\nThe value from the map becomes the value I choose. Example special should be a type integer, because that&#39;s what I put into the map is there a way to check this error at compile-time so it doesn&#39;t become a run-time error?\n\nBefore I post this code, this is going to look overly complicated you may ask why not just do this?\n\n\n\nYes that would do the same as what I&#39;m doing, but that fails to catch every cast at compilation time. I&#39;m trying to keep track of my type I put in as a value and retrieve it as the same type so it can be caught at compilation time.\n\nHere&#39;s my class so far.\n\nAttributeMap\n\n\n\nAttributeKey\n\n\n\nI can catch this problem by doing this.\n\n\n\nThough I don&#39;t want to specify the second parameter I want to hide that. Is that possible?\n",
        "excerpt": ");\n\n\nOutput without the run-time <span class=\"highlight\">error</span>\n\nspecial value: 100 running value: false\n\n\nThe value from the map becomes the value I choose. Example special should be a type integer, because that&#39;s what I put &hellip;  into the map is there a way to check this <span class=\"highlight\">error</span> at compile-time so it doesn&#39;t become a run-time <span class=\"highlight\">error</span>?\n\nBefore I post this code, this is going to look overly complicated you may ask why not just do &hellip; ",
        "title": "Java Compile-Time Type Checking For Polymorphic Collections"
    }, {
        "tags": ["java", "android", "acra"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 20096648,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468592533,
        "creation_date": 1384952338,
        "body": "The app is crashed, but ACRA doesn&#39;t come up. Heres the log:\n\n\n\nWhy it didn&#39;t work? Can&#39;t it handle NullPointerException? \n\nUpdate\nHere&#39;s the code snippet with doInBackground function of AsyncTask class where NullPointExcetion is raising\n\n\n\nI think the proble is that params[0] or params[1] or both are null but why ACRA didn&#39;t show up?\n\nUpdate2\n\nAnother error I have noticed\n\n\n",
        "excerpt": "The app is crashed, but ACRA doesn&#39;t come up. Heres the log:\n\n11-20 16:50:19.119: <span class=\"highlight\">ERROR</span>/ACRA(23345): ACRA caught a <span class=\"highlight\">RuntimeException</span> exception for com.buggyproject. Building report.\n11-20 16:50:19.539 &hellip; : <span class=\"highlight\">ERROR</span>/ACRA(23345): ACRA caught a <span class=\"highlight\">RuntimeException</span> exception for com.buggyproject. Building report.\n11-20 16:50:19.909: <span class=\"highlight\">ERROR</span>/ACRA(23345): com.buggyproject fatal <span class=\"highlight\">error</span> : An <span class=\"highlight\">error</span> occured while &hellip; ",
        "title": "ACRA doesn&#39;t work"
    }, {
        "tags": ["cassandra", "datastax", "cassandra-3.0"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38396309,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468586235,
        "creation_date": 1468586235,
        "body": "I am trying to report Cassandra 3.0 metrics to Graphite server using metrics-graphite as suggested here http://www.datastax.com/dev/blog/pluggable-metrics-reporting-in-cassandra-2-0-2. When there is no load on the cluster everything works fine and all metrics are reported properly. But if some load occurs, I receive following exception in system.log:\n\n\n\nThis message is repeated every time the reporter tries to get metrics on every Cassandra node and some metrics become unavailable. In order to receive the metrics again, I have to restart all Cassandra nodes, that is very impractical. I tried different metrics-graphite versions from 3.1.0 to 3.1.2 with the same issue.\n",
        "excerpt": " there is no load on the cluster everything works fine and all metrics are reported properly. But if some load occurs, I receive following exception in system.log:\n\n<span class=\"highlight\">ERROR</span> [metrics-graphite-reporter-1-thread-1 &hellip; ] 2016-07-13 08:21:23,580 ScheduledReporter.java:119 - <span class=\"highlight\">RuntimeException</span> thrown from GraphiteReporter#report. Exception was suppressed.\njava.lang.IllegalStateException: Unable to compute ceiling for max &hellip; ",
        "title": "Cannot collect metrics in Cassandra"
    }, {
        "tags": ["jpa", "odata", "olingo"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 37853761,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468582952,
        "creation_date": 1466065552,
        "body": "I implemented an OData V2 Service with Apache Olingo V2 in connectin with JPA using EclipseLink. All requests are working fine, but when it comes to the point, where I want to access a single property via GET request from an entity set like for the following URL:\n\n\n  http://localhost:8080/MyODataService/XXXXXX.svc/EntitySet(12345)/Property\n\n\nthe response in return is:\n\n\n\nThe class which extends the ODataJPASeviceFactory looks as follows:\n\n\n\nMy question now is: \nHow do I implement the functionality, so that I can do GET and POST requests not only for a whole entity set, but also for a single property of an entity set like I tried with the mentioned URL?\n",
        "excerpt": " property via GET request from an entity set like for the following URL:\n\n\n  http://localhost:8080/MyODataService/XXXXXX.svc/EntitySet(12345)/Property\n\n\nthe response in return is:\n\n&lt;<span class=\"highlight\">error</span> xmlns=&quot;http &hellip; ://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;\n&lt;code/&gt;\n           &lt;message xml:lang=&quot;de-DE&quot;&gt;Not implemented&lt;/message&gt;\n&lt;/<span class=\"highlight\">error</span>&gt;\n\n\nThe class which extends the ODataJPASeviceFactory looks as follows &hellip; ",
        "title": "Olingo OData V2 Read Property not implemented"
    }, {
        "tags": ["java", "akka"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 38379141,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468571257,
        "creation_date": 1468512516,
        "body": "I&#39;m reading Akka documentation and now I&#39;m at the section about UntypedActors. I decided to try some examples:\n\nHere are my actors:\n\nParent\n\n\n\nChild\n\n\n\nmain:\n\n\n\nso, my child actors experienced failure and I thought the it should have notified the parent somehow.\n\nBut what I recieved was this:\n\n\n\nWhat does the supervision do actually? Child actor had faulted and what? I got just an error message in a log. What does supervisorStrategy mean? It&#39;s by default set to\n\n\n",
        "excerpt": " {\n        System.out.println(&quot;My: &quot; + message);\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;Crashed: &quot; + getSelf());\n    }\n}\n\n\nmain:\n\npublic static void main(String[] args) throws TimeoutException {\n    ActorSystem system &hellip;  failure and I thought the it should have notified the parent somehow.\n\nBut what I recieved was this:\n\nRecieved: Message\nMy: Process it \n[<span class=\"highlight\">ERROR</span>] [07/14/2016 19:05:13.726] [default-akka.actor.default &hellip; ",
        "title": "Understanding supervisor strategy in Akka"
    }, {
        "tags": ["java", "json", "rest", "nullpointerexception"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 6,
        "is_answered": true,
        "question_id": 30117737,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1468512473,
        "creation_date": 1431068621,
        "body": "I&#39;m writing code in Java for REST and the output which I&#39;m getting is in JSON format. I want to parse the JSON string into a simple string in Java but I&#39;m getting errors. Below is my code:\n\n\n\nthe output is \n\n\n\nSo I want output as \n\n\n\n...  and so on\n",
        "excerpt": "();\n            conn.setRequestMethod(&quot;GET&quot;);\n            conn.setRequestProperty(&quot;Accept&quot;, &quot;application/json&quot;);\n\n            if (conn.getResponseCode() != 200) {\n\n                throw new <span class=\"highlight\">RuntimeException</span> &hellip; (&quot;Failed : HTTP <span class=\"highlight\">error</span> code : &quot;\n                        + conn.getResponseCode());\n            }\n\n            BufferedReader br = new BufferedReader(new InputStreamReader(\n            (conn.getInputStream &hellip; ",
        "title": "REST api and json parsing"
    }, {
        "tags": ["android", "dalvik", "android-version", "android-api-levels", "android-fingerprint-api"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 37553650,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468496703,
        "creation_date": 1464721325,
        "body": "I have a  that handles login and fingerprint authentication for my application. This fragment uses two classes that are exclusive to API 23,  and . I had been under the impression that I could use these classes, as long as I check the build version before I try to initialize the classes (outlined here):\n\n\n\nBut it appears that this is not the case. If I try to run this code on a version prior to API 20, the Dalvik VM rejects the entire class and throws a . Though, the code does work for API 20 and greater. How can I use these methods in my code while still allowing the code to be used for previous API levels?\n\nThe full stack trace is as follows:    \n\n\n\n\n\nUpdated with Code\n\nThe  method is just a convenience method to start the :\n\n\n\nThe relevant code is in the  itself. Specifically the  and  methods:\n\n\n\n\n\nUpdate\n\nOkay, so I figured out it is the  that is causing the error. If I comment out the  block that handles that exception, the code runs fine on any device. The problem is that I need to be able to handle that exception on devices on API 23+:\n\n\n",
        "excerpt": ", CharSequence message) {\n        Timber.i(&quot;Fingerprint <span class=\"highlight\">error</span> id: &quot; + messageId + &quot; message: &quot; + message);\n        if(messageId != 5) {\n            showFingerprintError(message);\n        }\n    }\n\n    @Override &hellip; \n                | NoSuchAlgorithmException | InvalidAlgorithmParameterException exception) {\n            throw new <span class=\"highlight\">RuntimeException</span>(&quot;Failed to initialize Cipher&quot;, exception);\n        }\n    }\n\n    private &hellip; ",
        "title": "How to Use Unsupported Exception for Lower Platform Version"
    }, {
        "tags": ["java", "spring", "rest", "resttemplate"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38370781,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468489316,
        "creation_date": 1468489316,
        "body": "Using Spring and RestTemplate I&#39;m trying to call into an external service which does not return the correct content type as part of the HTTP response. Both JSON response and XML responses are returned with a Content-Type of text/html. I would like to use the same RestTemplate instance to handle these requests with an appropriate HttpMessageConverter handling the different response types. In order to do this I would like to implement ClientHttpRequestInterceptor, detect the content type modify the response header as shown:\n\n\n\nHowever, this results in the following exception:\n\n\n\nWhat would be the correct way to modify the response headers prior to hitting the RestTemplate message converters?\n",
        "excerpt": ")) {\n        response.getHeaders().setContentType(MediaType.APPLICATION_XML);\n    } else {\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;Unexpected message type detected in response&quot;);\n    }\n\n    return response;\n}\n\n\nHowever &hellip; , this results in the following exception:\n\nRequest processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O <span class=\"highlight\">error</span> on POST request for &quot;https &hellip; ",
        "title": "How do I modify REST response headers in a Spring ClientHttpRequestInterceptor?"
    }, {
        "tags": ["android", "google-play-services", "google-oauth", "google-fit-sdk"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38255110,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468442162,
        "creation_date": 1467924946,
        "body": "I am looking for some fresh ideas on the dreaded 5005 error: &quot;Status code denotes that an unknown error occurred while trying to obtain an OAuth token.&quot; when my Watch Face tries to connect a Google API built with various Fitness APIs. This all works in my local testing AND when I download and run my RELEASE (beta) version. However, when my first tester tried it, he gets that error code when trying to connect the API.\n\nUPDATE2: I have now tracked down what is going on, so I&#39;m going to list my final working code here and then talk in the answer about what I discovered. \n\nThere are 3 different occasions where I connect to the Google API: the Watch Face (a referee timer: https://play.google.com/store/apps/details?id=com.pipperpublishing.soccerrefpro), the associated Watch Config, and the companion app on the Mobile (phone).\n\nWatch Face:\n\n\n\nNotice that I don&#39;t ask for WRITE permission for the HISTORY_API. When I later try to insert SPEED and LOCATION fitness data in the Google Fit store, I use this code:\n\n\n\nRemember this read-back code, because I&#39;ll reference the results in my answer.\n\nWatch Config\nThe difference here is that the Watch Config extends FragmentActivity:\n\n\n\nNotice here I ask for READ_WRITE scopes, although in reality I don&#39;t reference the HISTORY_API (or any Fitness Api) in the Config. However, the user has to go into the Watch COnfig to turn on my setting ( below) which controls reading Sensor data in the Watch Face.\n\nFinally,\nMobile\n\n\n",
        "excerpt": "I am looking for some fresh ideas on the dreaded 5005 <span class=\"highlight\">error</span>: &quot;Status code denotes that an unknown <span class=\"highlight\">error</span> occurred while trying to obtain an OAuth token.&quot; when my Watch Face tries to connect a Google &hellip;  API built with various Fitness APIs. This all works in my local testing AND when I download and run my RELEASE (beta) version. However, when my first tester tried it, he gets that <span class=\"highlight\">error</span> code when &hellip; ",
        "title": "Google Fit authorization bugs (with 5005, 5000, and 5015 errors) on WatchFace, WatchConfig, and companion app"
    }, {
        "tags": ["java", "spring-mvc", "exception-handling"],
        "question_score": 2,
        "is_accepted": true,
        "answer_id": 24394606,
        "is_answered": false,
        "question_id": 24393499,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1468420192,
        "creation_date": 1403637654,
        "body": "A few things I noticed.  First, use exceptions only for exceptional conditions.   Put another way, exceptions should be the exception, not the norm.  From what it looks like, &quot;ConstraintViolationException&quot; is something that is going to be expected a lot.\nExceptions make the code uglier, harder to debug, and reduce JVM optimizations that greatly speed up program execution. \n\nSecond, you should only use checked exceptions (exceptions that don&#39;t extend from RuntimeException) if the caller can be reasonable expected to recover.  In your case, the caller doesn&#39;t do anything to recover except give the client an error message. \nBy throwing a checked exception, you force the caller to handle the exception in a catch clause or propagate it outwards.  (Both are these pitfalls are detailed in Joshua Bloch&#39;s excellent book, &quot;Effective Java&quot;.)\n\nThird, in your exception handling, you try to parse the error message.  This can be very problematic because third parties often change their error messages, because they\nare not a part of the API.  Once this happens, you&#39;re code is broken.  Another minor problem in your exception handling is that tie your JPA implementation to hibernate.  What if later you want to change to EclipseLink?\n\nThere is a way to address all these issues.\nGet rid of the exception handling in your DAO.\nAdd the following method to your DAO:\n\n\n\nThen, in your controller, have something like:\n\n\n\nYou will need some sort of exceptionHandler in the controller.  (If you&#39;re using Spring MVC, you can just add it as another method using the ExceptionHandler annotation.)\nThis would address things that are truly exceptions (things that are out of the ordinary for the everyday user experience, and things that the user can&#39;t fix.)\n",
        "excerpt": " only use checked exceptions (exceptions that don&#39;t extend from <span class=\"highlight\">RuntimeException</span>) if the caller can be reasonable expected to recover.  In your case, the caller doesn&#39;t do anything to recover except give &hellip;  the client an <span class=\"highlight\">error</span> message. \nBy throwing a checked exception, you force the caller to handle the exception in a catch clause or propagate it outwards.  (Both are these pitfalls are detailed in Joshua &hellip; ",
        "title": "Exception Handling for specific condition - Best Practice"
    }, {
        "tags": ["java", "ssl", "apache-httpclient-4.x"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38352678,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468415306,
        "creation_date": 1468415306,
        "body": "I&#39;m trying to setup 2 way ssl authentication with Apache HTTP client. Below is my code extract that I used to call rest services.\n\n\n\nThe problem is this code works fine in my DEV and QA environment but while testing in PRODUCTION , I get handshake failure. Upon setting &quot;javax.net.debug&quot; to &quot;ssl&quot;\n\n\n\nI don&#39;t know how to decode above SSL logs.\n",
        "excerpt": ");\n              sb.append(line);\n              }\n            //throw new <span class=\"highlight\">RuntimeException</span>(&quot;Failed with HTTP <span class=\"highlight\">error</span> code : &quot; + statusCode);\n        }\n        return sb.toString();\n\n\nThe problem &hellip; ",
        "title": "Recived fatal hanshake_failure in 2way SSL authentication"
    }, {
        "tags": ["android", "android-emulator", "audiorecord"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38347723,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468402135,
        "creation_date": 1468402135,
        "body": "My app is recording audio from phone&#39;s microphones and does some real time processing on it. It&#39;s working fine on physical devices, but acts &quot;funny&quot; in emulator. It records something, but I&#39;m not quite sure what it is it&#39;s recording. \n\nIt appears that on emulator the audio samples are being read at about double the rate as on actual devices. In the app I have a visual progress widget (a horizontally moving recording head), which moves about twice as fast in emulator. \n\nHere is the recording loop:\n\n\n\nThe audio source is set to &quot;CAMCORDER&quot; and it records in stereo. The idea is, if the phone has multiple microphones, the app will process data from both and use whichever has better SNR. But I have the same problems if recording mono from . It reads audio data in a  loop, I am assuming that  is a blocking call and will not let me read same data twice.\n\nThe recorded data looks OK – the record buffer contains 16-bit PCM samples for two channels. The loop just seems to be running at twice the speed as on real devices. Which leads me to think that maybe the emulator is using a higher sampling rate than the specified 44100Hz. If I query the sample rate with  it returns the correct value. \n\nAlso there are some interesting audio related messages in logcat while recording:\n\n\n\nI&#39;m using up-to-date Android Studio and Android SDK, and I have tried emulator images running API levels 21-24. My dev environment is Ubuntu 16.04\n\nHas anybody experienced something similar? \nAm I doing something wrong in my recording loop? \n",
        "excerpt": " bufferReadResult = audioRecord.read(signal, 0, BLOCKSIZE * 2);\n    if (bufferReadResult != BLOCKSIZE * 2)\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;Recorded less than BLOCKSIZE x 2 samples &hellip; : mixer(0xf44c0000) throttle end: throttle time(154)\n(...)\n07-13 12:22:02.373  1187  1817 E audio_hw_generic: <span class=\"highlight\">Error</span> opening input stream format 1, channel_mask 0010, sample_rate 16000\n07-13 12:22:02.373 &hellip; ",
        "title": "Android Emulator Seems to Record Audio at 96khz"
    }, {
        "tags": ["android", "video-capture", "nexus", "camera2"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38094822,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468401460,
        "creation_date": 1467190754,
        "body": "I try to implement high speed capture session by click on button. Here is my state callback:\n\n\n\nopen camera method:\n\n\n\ncalled when started preview and onClick event\n\n\n\nupdate preview is called above\n\n\n\nThe first time all is went right, but, when I try to start app again there is an error while open camera device, error code 1 in callback.\nWithout running high fps all is good. To escape this issue device must be rebooted, that mystified me\n\nreleasingCamera:\n\n\n\nHere is a background thread for camera:\n\n\n",
        "excerpt": " cameraDevice) {\n        mCameraOpenCloseLock.release();\n        cameraDevice.close();\n        mCameraDevice = null;\n    }\n\n    @Override\n    public void onError(CameraDevice cameraDevice, int <span class=\"highlight\">error</span> &hellip; (), null, mHandler);\n        }\n    } catch (Exception e) {\n        e.printStackTrace();\n    }\n}\n\n\nThe first time all is went right, but, when I try to start app again there is an <span class=\"highlight\">error</span> while open camera &hellip; ",
        "title": "Issue with Nexus 6P : configure 60 fps preview session using camera 2 api"
    }, {
        "tags": ["mocking", "apache-kafka"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38346245,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468398060,
        "creation_date": 1468398060,
        "body": "I would expect a  constructed with  to not add a message to its  until  has been called.  If  is called I would expect such a message not to appear in .  But it does.  Indeed  adds messages as soon as it&#39;s been called regardless of .\n\nThis test illustrates my point (I&#39;m using kafka 0.10.0.0):\n\n\n\nKAFKA-3956 has also been raised to open this problem ... assuming I&#39;m not doing something wrong :)\n",
        "excerpt": " should be empty ... but isn&#39;t\n    Assert.assertTrue(mockProducer.history().isEmpty());\n    // Cause the next operation to fail\n    Assert.assertTrue(mockProducer.errorNext(new <span class=\"highlight\">RuntimeException</span>(&quot;Force &hellip;  an <span class=\"highlight\">error</span>&quot;)));\n    System.out.println(&quot;Mock producer contains &quot; + mockProducer.history().size() + &quot; message(s)&quot;);\n    // We&#39;re too late ... the message has already been &quot;sent&quot;\n    Assert.assertTrue &hellip; ",
        "title": "Kafka&#39;s MockProducer.send() sends a message before completeNext() or errorNext() are called"
    }, {
        "tags": ["orientation", "android-camera2"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38282076,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468363597,
        "creation_date": 1468069204,
        "body": "Here is my camera fragment, in which i am opening the camera using TextureView. The camera is capturing the image in correct orientation but the captured image is not getting saved in correct orientation...\n\n\n",
        "excerpt": "();\n            cameraDevice.close();\n            mCameraDevice = null;\n        }\n\n        @Override\n        public void onError(@NonNull CameraDevice cameraDevice, int <span class=\"highlight\">error</span> &hellip;  <span class=\"highlight\">RuntimeException</span>(&quot;Time out waiting to lock camera opening.&quot;);\n            }\n            manager.openCamera(mCameraId, mStateCallback, mBackgroundHandler);\n        } catch (CameraAccessException e &hellip; ",
        "title": "Hot to Save images in correct orientation using CAMERA2"
    }, {
        "tags": ["scala", "akka", "actor", "akka-stream"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 38195062,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468337950,
        "creation_date": 1467691922,
        "body": "I am trying to materialise a graph within an actor. This seems to work if either of the following are true:\n\n\nThe graph does not contain a broadcast (created with ), or\nThe same  is used for each materialisation, or\nThe graph is materialised outside of an \n\n\nI have reduced it down to the following test cases:\n\n\n\nIt seems that the last cases will always timeout with the following error in the log:\n\n\n\nI have tried explicitly terminating the  but that doesn&#39;t reproduce the problem.\n\nA workaround is to create a closure around the  in the  but if this also came from another  I&#39;m worried I will eventually get similar problems.\n\nAny idea why this is? Obviously it is something to do with the  but interesting how removing the Broadcast also solves it (even with a much more complicated graph).\n",
        "excerpt": "()\n    }\n\n    override def receive: Receive = {\n      case Bomb =&gt; throw new <span class=\"highlight\">RuntimeException</span>\n    }\n  }\n\n  &quot;Without an actor&quot; should &quot;be able to materialize twice&quot; in {\n    val graph = Source.empty.alsoTo &hellip;  = {\n    actorRef.start()\n    actorRef ! Bomb\n    latch.await(25, TimeUnit.SECONDS)\n  }\n}\n\n\nIt seems that the last cases will always timeout with the following <span class=\"highlight\">error</span> in the log:\n\n[<span class=\"highlight\">ERROR</span>] [07/05/2016 16:06:30.625 &hellip; ",
        "title": "Materialising a graph within an actor"
    }, {
        "tags": ["android", "opengl-es", "augmented-reality", "google-cardboard"],
        "question_score": 3,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 38227842,
        "item_type": "question",
        "score": 3,
        "last_activity_date": 1468321756,
        "creation_date": 1467818935,
        "body": "I tried to develop a mobile cardboard application, which renders 3d objects into a camera view (some kind of ar).\n\nI used this project and tried to render a simple cube in the camera:\nhttps://github.com/Sveder/CardboardPassthrough/\n\nI didn&#39;t get it working, the background is always black or the app wrecked.\n\nI would be very grateful for any help or suggestions.\n\nThanks\n\nThats what i have\n\n\nOrigin CardboardPassthrough\n\n\nhere is the working code, with the cubes\n\n\n\nEdit 11.07.16\n\nI cut the vertex in half, to see posible vertex behind it.\nBut i think the problem is vertex and fragment-shader\n\nThe Cube is only showing up, when im using this vertex and fragment-shader\n\n\n  simple_fragment.shader\n\n\n\n\n\n  light_vertex.shader\n\n\n\n\nand the camera is only showing up when im using this shaders\n\n\n  vertex.shader\n\n\n\n\n\n  fragment.shader\n\n\n\n\ni don&#39;t know how to fix the shaders\n\n\n",
        "excerpt": ") {\n        GLES20.glDeleteShader(shader);\n        shader = 0;\n    }\n\n    if (shader == 0) {\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;<span class=\"highlight\">Error</span> creating shader.&quot;);\n    }\n\n    return shader;\n}\n\n/**\n * Checks &hellip; ()) != GLES20.GL_NO_ERROR) {\n        throw new <span class=\"highlight\">RuntimeException</span>(func + &quot;: glError &quot; + <span class=\"highlight\">error</span>);\n    }\n}\n\n/**\n * Sets the view to our CardboardView and initializes the transformation matrices we will use &hellip; ",
        "title": "Render 3d Objects into Cameraview"
    }, {
        "tags": ["asynchronous", "file-upload", "jersey", "multipart", "server-sent-events"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38322445,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468312626,
        "creation_date": 1468308251,
        "body": "I&#39;m using Jersey Multipart for uploading file to the server via Rest API. In the resource method, I accessed the file content via InputStream. I want to return the uploaded file size to the client with EventOutput using SSE so the client easily get the uploaded file size directly from upload resource method.\nI&#39;m using Jersey as JAX-RS implementation in java with Grizzly Http server. Here is my code:\n\n\n\n​\nThe problem is when my resource method return EventOutput as a response and request processing thread back to the I/O container, the InputStream closed and the processing thread can&#39;t access to the uploaded file. Here is the exception:\n\n\n\n​\n1- What&#39;s the problem in the code? Why InputStream is closed in the middle of the file transfer?\n2- Is there any alternative way to return the uploaded file size to the client in server side? (REQUIREMENT: the upload resource method must  handle upload file asynchronously in different thread)\n",
        "excerpt": ") {\n                    throw new <span class=\"highlight\">RuntimeException</span>(\n                            &quot;<span class=\"highlight\">Error</span> when writing the event.&quot;, e);\n                } finally {\n                    try &hellip;  {\n                        eventOutput.close();\n                    } catch (Exception ioClose) {\n                        throw new <span class=\"highlight\">RuntimeException</span>(\n                                &quot;<span class=\"highlight\">Error</span> when closing the event output.&quot;, ioClose &hellip; ",
        "title": "​ InputStream closed unexpectedly while using Jersey MultiPart file upload &amp; Server-Sent Events (SSE)"
    }, {
        "tags": ["java", "rest", "client", "mapping"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38323759,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468312527,
        "creation_date": 1468312527,
        "body": "I try to map a rest service (JSON) to POJOs. On Client side i use resteasy on server side i use Glassfish and Jersy. The rest service is working well.\n\nWhat is working, but not mapping\n\n\n\nOk, this working. I get the String representation of JSON from Server\n\nWhat is thrown an exception\n\n\n\nNot ok, this not working. I get an Exception of Unrecognized Type: [null]. Have somebody an idea?\n\nMyClient class\n\n\n",
        "excerpt": "(form));\nif (jsonAnswer.getStatus() != 200) {\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;Failed : HTTP <span class=\"highlight\">error</span> code : &quot;\n                + jsonAnswer.getStatus());\n}\n//System.out.println(jsonAnswer.readEntity &hellip; ",
        "title": "Mapping from json rest service to pojo"
    }, {
        "tags": ["java", "ssl-certificate", "vmware", "host"],
        "question_score": -4,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38260561,
        "item_type": "question",
        "score": -4,
        "last_activity_date": 1468307525,
        "creation_date": 1467960673,
        "body": "I am getting a null pointer exception at his point of the code:\n\n\n\nhostSystem1 is the host&#39;s managed object reference.\nwaitFOrValues is the object of WaitForValues (of com.vmware.connection.helpers.WaitForValues)\n\nCan someone help with this? The total java code is given below:\n\n\n\nWaitForValues.java comes from com.vmware.connection.helpers. Code is as follows: \n\n\n",
        "excerpt": "(&quot;Executing UploadGuestFile guest operation&quot;);\n\n    File file = new File(localFilePath);\n    if (!file.exists()) {\n        System.out.println(&quot;<span class=\"highlight\">Error</span> finding the file: &quot; + localFilePath &hellip;  <span class=\"highlight\">RuntimeException</span> {\n    private static final long serialVersionUID = 1L;\n\n    public UploadException(String message) {\n        super(message);\n    }\n}\n\n\npublic static void main(String[] args) throws Exception &hellip; ",
        "title": "NullPointerException at com.vmware.connection.helpers.WaitForValues.wait"
    }, {
        "tags": ["apache-spark", "pyspark", "hadoop2", "google-cloud-dataproc", "aws-kinesis"],
        "question_score": 2,
        "is_accepted": false,
        "answer_id": 38308008,
        "is_answered": false,
        "question_id": 38237345,
        "item_type": "answer",
        "score": 1,
        "last_activity_date": 1468282935,
        "creation_date": 1468243026,
        "body": "Our team was in a similar situation and we managed to solve it:\n\nWe are running on the same environment:\n\n\nDataProc Image Version 1 with Spark 1.6.1 with Hadoop 2.7\nA simple SparkStream Kinesis Script that boils down to this:\n\n\nThe code had been tested working on AWS EMR and on local environment using the same Spark 1.6.1 with Hadoop 2.7 setup. \nThe script is returning empty RDDs without printing any error while there is data in the Kinesis stream on DataProc.\nWe&#39;ve tested it on DataProc with the following envs, and none of them worked. \n\n\nSubmit job via  command;\n into Cluster Master Node and run in  client mode;\n into Cluster Master Node and run as .\n\n\n\n\n\nUpon enabling verbose logging by updating  with the following value:\n\n\n\n\n\nWe&#39;ve notice something weird in the log(Note that  uses  as dependence while somehow  was used [suggested by user-agent]):\n\n\n\n\n\nIt appears that DataProc had build its own Spark with a much older AWS SDK as dependencies and it will blow up when used in conjunction with codes that requires much newer version of AWS SDK although we are not sure exactly which module had cause this error.\n\nUpdate:\nBase on @DennisHuo&#39;s comment, this behaviour is caused by Hadoop&#39;s leaky classpath:\nhttps://github.com/apache/hadoop/blob/branch-2.7.2/hadoop-project/pom.xml#L650\n\nTo make things worst, the AWS KCL 1.4.0 (used by Spark 1.6.1) will suppress any runtime error silently instead of throwing  and causing a lot of headache while debugging.\n\n\n\nEventually Our solution was to build our  with all of its  shaded.\n\nBuilding the JAR with the following pom (update ) and shit the new JAR with  flag in \n\n\n",
        "excerpt": "\n\nTo make things worst, the AWS KCL 1.4.0 (used by Spark 1.6.1) will suppress any runtime <span class=\"highlight\">error</span> silently instead of throwing <span class=\"highlight\">RuntimeException</span> and causing a lot of headache while debugging &hellip;  the same Spark 1.6.1 with Hadoop 2.7 setup. \nThe script is returning empty RDDs without printing any <span class=\"highlight\">error</span> while there is data in the Kinesis stream on DataProc.\nWe&#39;ve tested it on DataProc &hellip; ",
        "title": "Kinesis Stream with Empty Records in Google Dataproc with Spark 1.6.1 Hadoop 2.7.2"
    }, {
        "tags": ["asynchronous", "nonblocking", "completable-future"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 38313061,
        "is_answered": false,
        "question_id": 38254268,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1468259035,
        "creation_date": 1468259035,
        "body": "Looks like it runs in the same executor as its CompletionStage\n\n\n\nFor fixed size:\n\n\n  async thread at 418000000 -&gt; pool-1-thread-1\n  \n  error thread for 418000000 -&gt; pool-1-thread-1\n  \n  async thread at 646000000 -&gt; pool-1-thread-2\n  \n  error thread for 646000000 -&gt; pool-1-thread-2\n  \n  async thread at 646000000 -&gt; pool-1-thread-3\n  \n  error thread for 646000000 -&gt; pool-1-thread-3\n  \n  async thread at 646000000 -&gt; pool-1-thread-1\n  \n  error thread for 646000000 -&gt; pool-1-thread-1\n  \n  async thread at 647000000 -&gt; pool-1-thread-2\n  \n  error thread for 647000000 -&gt; pool-1-thread-2\n\n\nFor stealing pool(4 cores):\n\n\n  async thread at 96000000 -&gt; ForkJoinPool-1-worker-1\n  \n  error thread for 96000000 -&gt; ForkJoinPool-1-worker-1\n  \n  async thread at 196000000 -&gt; ForkJoinPool-1-worker-1\n  \n  error thread for 196000000 -&gt; ForkJoinPool-1-worker-1\n  \n  async thread at 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  error thread for 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  async thread at 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  error thread for 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  async thread at 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  error thread for 197000000 -&gt; ForkJoinPool-1-worker-1\n  \n  async thread at 197000000 -&gt; ForkJoinPool-1-worker-1\n\n\nwith no executor:\n\n\n  async thread at 848000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  error thread for 848000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  async thread at 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  error thread for 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  async thread at 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  error thread for 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  async thread at 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  error thread for 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  async thread at 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n  \n  error thread for 944000000 -&gt; ForkJoinPool.commonPool-worker-1\n\n",
        "excerpt": " {\n                        TimeUnit.SECONDS.sleep(2);\n                    } catch (InterruptedException e) {\n                        e.printStackTrace();\n                    }\n                    throw new <span class=\"highlight\">RuntimeException</span> &hellip; ();\n                }, executorService);\n\n        completableFuture.exceptionally(\n                (err)-&gt; {\n                    System.err.printf(&quot;<span class=\"highlight\">error</span> thread for %d -&gt; %s\\n&quot;, i, Thread.currentThread().getName &hellip; ",
        "title": "CompletableFuture.exceptionally with executor"
    }, {
        "tags": ["datasource", "wildfly"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38309360,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468248426,
        "creation_date": 1468246972,
        "body": "I&#39;m using WildFly 10.0.0 and MySQL 5.5.17 and JDBC Driver 5.1.39\n\nI first set a  in WildFly as a module\n\nid the folder WILDFLY_HOME\\modules\\system\\layers\\base\\com\\mysql\\main there is the driver and the file  :\n\n\n\nAnd the config file  :\n\n\n\nWhen I test the connection within the wildfly console I have the message : &quot;Successfully created JDBC connection.\nSuccessfully connected to database MyDS&quot;\n\nWhen I try to use this  doing :\n\n\n\nI have this  :\n\n\n\nWhen I do :\n\n\n\nIt works...\n\nHow I have to handle ? Do problems will occurs if I don&#39;t close ? Maybe it&#39;s a problem of  config...\n",
        "excerpt": ";\n                }\n            }\n        }\n    } catch (Exception e) {\n        throw new <span class=\"highlight\">RuntimeException</span>(e);\n    }\n}\n\n\nI have this Exception :\n\nThe last packet successfully received from the server was 2&#160;621&#160;144 &hellip; : socket write <span class=\"highlight\">error</span>\nat java.net.SocketOutputStream.socketWrite0(Native Method)\nat java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)\nat java.net.SocketOutputStream.write &hellip; ",
        "title": "Closing Connection from WildFly Datasource cause java.net.SocketException"
    }, {
        "tags": ["php", "class", "exception", "exception-handling"],
        "question_score": 20,
        "is_accepted": true,
        "answer_id": 10838284,
        "is_answered": false,
        "question_id": 10838257,
        "item_type": "answer",
        "score": 44,
        "last_activity_date": 1468239143,
        "creation_date": 1338484922,
        "body": "PHP 5 has two built in exceptions\n\n\n\n\n\n\nSPL includes a few of its own built in exceptions:\n\n\n The method call was illegal.\n A callback refers to an undefined method or if some arguments are missing.\n A value does not adhere to a defined valid data domain.\n The arguments passed were invalid.\n The parameter exceeds the allowed length (used for strings, arrays, file size, etc.).\n Generic error occured in program logic.\n An illegal index was requested.\n An illegal index was requested. This represents errors that should be detected at compile time.\n Adding an element to a full container.\n Indicate range errors during program execution. Normally this means there was an arithmetic error other than under/overflow.\n An error which can only be found on runtime occurs.\n Performing an invalid operation on an empty container, such as removing an element.\n An unexpected value was received (i.e. as the result of a returned value from a method call).\n\n\nPHP 7 introduces new exceptions including catchable errors. New exceptions include:\n\n\n is the base interface for any object that can be thrown via a throw statement in PHP 7, including Error and Exception.\n is the base class for all internal PHP errors.\n is thrown when an assertion made via assert() fails.\n is thrown when an error occurs while parsing PHP code, such as when eval() is called.\n There are three scenarios where a TypeError may be thrown. The first is where the argument type being passed to a function does not match its corresponding declared parameter type. The second is where a value being returned from a function does not match the declared function return type. The third is where an invalid number of arguments are passed to a built-in PHP function (strict mode only).\n\n\nHere&#39;s a chart that demonstrates the new hierarchy introduced in PHP 7:\n\n\n",
        "excerpt": " Indicate range errors during program execution. Normally this means there was an arithmetic <span class=\"highlight\">error</span> other than under/overflow.\n<span class=\"highlight\">RuntimeException</span> An <span class=\"highlight\">error</span> which can only be found on runtime occurs &hellip;  (extends \\<span class=\"highlight\">RuntimeException</span>)\n│       ├── \\UnderflowException (extends \\<span class=\"highlight\">RuntimeException</span>)\n│       └── \\UnexpectedValueException (extends \\<span class=\"highlight\">RuntimeException</span>)\n└── \\<span class=\"highlight\">Error</span> (implements \\Throwable)\n    ├── \\AssertionError (extends \\<span class=\"highlight\">Error</span>)\n    ├── \\ParseError (extends \\<span class=\"highlight\">Error</span>)\n    └── \\TypeError (extends \\<span class=\"highlight\">Error</span>)\n\n &hellip; ",
        "title": "What Exception subclasses are built into PHP?"
    }],
    "name": "RuntimeException an error"
}, {
    "items": [{
        "tags": ["android"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38410974,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468675139,
        "creation_date": 1468670374,
        "body": "I try upload image to local server and it successfully, but when I try upload to my database online some times there have error in code \n\nthis my code..\n\n\n\nand this is the logcat\n\n\n",
        "excerpt": "I try upload image to local server and it successfully, but when I try upload to my database online some times there have <span class=\"highlight\">error</span> in code task.execute(FIXURL+&quot;upload_WC.php&quot;);\n\nthis my code..\n\npublic &hellip; {\n                        Toast.makeText(getApplicationContext(), &quot;<span class=\"highlight\">Error</span> while uploading.&quot;,\n                                Toast.LENGTH_SHORT).show();\n                    }\n                }\n            });\n\n            task.execute &hellip; ",
        "title": "android PostResponseAsyncTask some times error when url is online and no if in local server"
    }, {
        "tags": ["hadoop", "apache-pig"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38410936,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468672270,
        "creation_date": 1468669980,
        "body": "When I run the pig in local mode, it is running fine but in map reduce mode \nit is throwing error message  \n\n\n\n\n  2016-07-16 17:19:40,973 [main] ERROR org.apache.pig.tools.grunt.Grunt\n  - ERROR 2997: Encountered IOException. File or directory null does not exist. Details at logfile: /home/hduser/pig_1468666911969.log\n\n\nPlease find the stack trace:\n\n    Pig Stack Trace\n\n\n  ERROR 2997: Encountered IOException. File or directory null does not\n  exist.\n  \n  java.io.IOException: File or directory null does not exist.   at\n  org.apache.pig.tools.grunt.GruntParser.processLS(GruntParser.java:848)\n    at\n  org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:485)\n    at\n  org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:230)\n    at\n  org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:205)\n    at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)  at\n  org.apache.pig.Main.run(Main.java:565)    at\n  org.apache.pig.Main.main(Main.java:177)   at\n  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)   at\n  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n    at\n  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n    at java.lang.reflect.Method.invoke(Method.java:498)     at\n  org.apache.hadoop.util.RunJar.run(RunJar.java:221)    at\n  org.apache.hadoop.util.RunJar.main(RunJar.java:136)\n\n\nThanks in advance.\n",
        "excerpt": "\n  - <span class=\"highlight\">ERROR</span> 2997: Encountered <span class=\"highlight\">IOException</span>. File or directory null does not exist. Details at logfile: /home/hduser/pig_1468666911969.log\n\n\nPlease find the stack trace:\n\n    Pig Stack Trace\n\n\n  <span class=\"highlight\">ERROR</span> 2997 &hellip; When I run the pig in local mode, it is running fine but in map reduce mode \nit is throwing <span class=\"highlight\">error</span> message  \n\ngrunt&gt; ls\n\n\n\n  2016-07-16 17:19:40,973 [main] <span class=\"highlight\">ERROR</span> org.apache.pig.tools.grunt.Grunt &hellip; ",
        "title": "Pig isn&#39;t working in mapreduce mode"
    }, {
        "tags": [".net", "windows", "file"],
        "question_score": 33,
        "is_accepted": true,
        "answer_id": 324345,
        "is_answered": false,
        "question_id": 324045,
        "item_type": "answer",
        "score": 38,
        "last_activity_date": 1468586961,
        "creation_date": 1227808043,
        "body": "The short answer: they don&#39;t get deleted.\n\nThe long answer: \nThe managed  method calls the native Win32API  method, like this: \n\n\n\nThe documentation for the native method states:\n\n\n   Temporary files whose names have been created by this function are not automatically deleted. To delete these files call DeleteFile.\n\n\nI have found a great article called &quot;Those pesky temp files&quot; (Archived Oct. 2007) that starts from basics and touches some less obvious problems of handling temporary files, like:\n\n\nHow to make sure the file is deleted (even if the app crashes! hint:  and let the kernel deal with it)\nHow to get the correct caching policy for the file, to improve performance  (hint: )\nHow to make sure the contents of the file stay secure, because:\n\n\nthe file name is even more predictable with the managed method than with the unmanaged one\nthe temp file is created, then closed, then you get the path to it (only to open it again), thus leaving a small window of opportunity for malicious code/users to hijack the file. \n\n\n\nC# Code from article:\n\n\n",
        "excerpt": "=&quot;<span class=\"highlight\">IOException</span>&quot;/&gt; if no unique temporary file name is available. Although this is possible, it is highly improbable. To resolve this <span class=\"highlight\">error</span>, delete all uneeded temporary files.&lt;/para&gt;\n    /// &lt;para &hellip;  is guaranteed to be unique to the system&#39;s temporary folder.&lt;/para&gt;\n    /// &lt;para&gt;The &lt;see cref=&quot;GetSecureDeleteOnCloseTempFileStream&quot;/&gt; method will raise an &lt;see cref=&quot;<span class=\"highlight\">IOException</span>&quot;/&gt; if no unique temporary &hellip; ",
        "title": "Windows temporary files behaviour - are they deleted by the system?"
    }, {
        "tags": ["java", "android"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38395669,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468584236,
        "creation_date": 1468584236,
        "body": "The idea is simple: I want to take a photo and store it. I get the following error, whenever I try to run it on and Android device:\n\n\n\nFunny enough, whenever I run it on an emulator, I don&#39;t get said error, but I can&#39;t take a picture &#39;cause I don&#39;t have access to the camera.\n\nMainActivity:\n\n\n\nIgnore onActivityResult, as it just ouputs a thumbnail of the taken photo.\n\nManifest:\n\n\n\nXML/file_paths:\n\n\n",
        "excerpt": " photoFile = null;\n            try {\n                photoFile = createImageFile();\n            } catch (<span class=\"highlight\">IOException</span> ex) {\n                // <span class=\"highlight\">Error</span> occurred while creating the File &hellip; The idea is simple: I want to take a photo and store it. I get the following <span class=\"highlight\">error</span>, whenever I try to run it on and Android device:\n\n    java.lang.RuntimeException: Unable to get provider &hellip; ",
        "title": "Unable to get provider android.support.v4.content.FileProvider when trying to take a photo and store it"
    }],
    "name": "IOException Error"
}, {
    "items": [{
        "tags": ["amazon-web-services", "amazon", "amazon-cognito"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38384136,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468568012,
        "creation_date": 1468529967,
        "body": "I&#39;m using AWS login example, but I&#39;m having a problem.\n\nhttps://github.com/awslabs/aws-sdk-android-samples/tree/master/CognitoSyncDemo\n\nOnce I log in,  I save the (Developer Authenticatiion) login credentials using the setLogins method. \n\n/**\n     * Sets the login so that you can use authorized identity. This requires a\n     * network request, so you should call it in a background thread.\n     * \n     * @param providerName the name of the external identity provider\n     * @param token openId token\n     */\n    public static void addLogins(String providerName, String token) {\n        if (syncClient == null) {\n            throw new IllegalStateException(&quot;CognitoSyncClientManager not initialized yet&quot;);\n        }\n\n\n\nHowever, this information is not persisted into the example. Thus, If I close and open my app application, the credentialsProvider.getLogins() will be empty. \n\nThe AWS example is not persisting the login map. There is something wrong with it? Without any information on the login map, I got a error \n\ncom.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access\n",
        "excerpt": " credentials using the setLogins method. \n\n/**\n     * Sets the login so that you can use authorized identity. This requires a\n     * network request, so you <span class=\"highlight\">should</span> <span class=\"highlight\">call</span> it in a background thread &hellip; ) {\n        if (syncClient == null) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;CognitoSyncClientManager not initialized yet&quot;);\n        }\n\n    Map&lt;String, String&gt; logins = credentialsProvider.getLogins();\n    if (logins &hellip; ",
        "title": "Dealing with Login Map in Cognito"
    }, {
        "tags": ["android", "onclicklistener", "android-recyclerview", "android-cursor", "android-cursorloader"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 37509486,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1464523063,
        "creation_date": 1464522111,
        "body": "I am working on a project which include  and  and when user clicks on an item in  it should get the data from item and start new .But instead it is giving me an exception \n \n\nMy Adapter :\n\n\n\nCursor Adapter :\n\n\n\ni would really appreciate if any of you guys Know a better solution than this to initiate an onclicklistenter and get the Cursor at Items position.\n\nThank you\n",
        "excerpt": " viewHolder, int position) {\n            if (!mDataValid) {\n                throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor is valid &hellip; I am working on a project which include Recyclerview and Cursorloader and when user clicks on an item in recyclerview it <span class=\"highlight\">should</span> get the data from item and start new Activity.But instead it is giving &hellip; ",
        "title": "Android Recyclerview Onclicklistener not working with Cursor"
    }, {
        "tags": ["android", "android-recyclerview"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 37475854,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1464349896,
        "creation_date": 1464328724,
        "body": "I have two activities MainActivity and Addlogactivity i am updating a data in Addlogactivity which should be displayed in mainactivity recyclerview the data is not updating in database \n\nMianActivityClass :\n\n\n\nAddLog activity class :\n\n\n\nContent Provider class:\n\n\n\nCursor Recyclerview Adapter class:\n\n\n\nMain Adapter class:\n\n\n",
        "excerpt": " void onBindViewHolder(VH viewHolder, int position) {\n        if (!mDataValid) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor is valid &hellip; I have two activities MainActivity and Addlogactivity i am updating a data in Addlogactivity which <span class=\"highlight\">should</span> be displayed in mainactivity recyclerview the data is not updating in database &hellip; ",
        "title": "How to update Recyclerview data from another activity"
    }, {
        "tags": ["android", "android-contentprovider", "android-recyclerview", "android-cursoradapter", "android-cursorloader"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 37474806,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1464342640,
        "creation_date": 1464322884,
        "body": "I am working on a project where user adds data at runtime.The problem is whenever user inserts the fist element it is adding to the database and displaying in recyclerview.But when user adds more data the recyclerview keeps displaying firstelement over and over again.\nIf the user adds  it is adding to database and recyclerview is displaying .Now if the user adds  it is adding to database but the recyclerview is displaying  two times.\nI am using Cursorloader to load data,Contentprovider to add data,and CustomCursoradapter(https://gist.github.com/skyfishjy/443b7448f59be978bc59) to set the data to recyclerview\n\n method execute when user adds data\n\n\n\nContent Provider class:\n\n\n\n}\n\nDetils class:\n\n\n\nAdapter class :\n\n\n\nCursor Recyclerview Adapter class:\n\n\n\nThank you\n",
        "excerpt": ") {\n        if (!mDataValid) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor is valid&quot;);\n        }\n        if (!mCursor.moveToPosition(position)) {\n            throw new &hellip;  <span class=\"highlight\">IllegalStateException</span>(&quot;couldn&#39;t move cursor to position &quot; + position);\n        }\n        onBindViewHolder(viewHolder, mCursor);\n    }\n\n    /**\n     * Change the underlying cursor to a new cursor &hellip; ",
        "title": "Recyclerview not refreshing"
    }, {
        "tags": ["java", "jpa", "cdi", "entitymanager", "java-ee-7"],
        "question_score": 11,
        "is_accepted": false,
        "answer_id": 30007786,
        "is_answered": false,
        "question_id": 19431423,
        "item_type": "answer",
        "score": 8,
        "last_activity_date": 1464320225,
        "creation_date": 1430602742,
        "body": "You&#39;re almost right on with your CDI producer. Only thing is that you should use a producer method instead of a producer field.\n\nIf you&#39;re using Weld as CDI container (GlassFish 4.1 and WildFly 8.2.0), then your example of combining ,  and  on a producer field should throw this exception during deployment:\n\n\n  org.jboss.weld.exceptions.DefinitionException: WELD-001502:\n  Resource producer field [Resource Producer Field [EntityManager] with\n  qualifiers [@Any @Default] declared as [[BackedAnnotatedField]\n  @Produces @RequestScoped @PersistenceContext\n  com.somepackage.EntityManagerProducer.entityManager]] must be\n  @Dependent scoped\n\n\nTurns out that the container is not required to support any other scope than @Dependent when using a producer field to lookup Java EE resources.\n\nCDI 1.2, section 3.7. Resources:\n\n\n  The container is not required to support resources with scope other\n  than @Dependent. Portable applications should not define resources\n  with any scope other than @Dependent.\n\n\nThis quote was all about producer fields. Using a producer method to lookup a resource is totally legit:\n\n\n\nFirst, the container will instantiate the producer and a container-managed entity manager reference will be injected into the  field. Then the container will call your producer method and wrap what he returns in a request scoped CDI proxy. This CDI proxy is what your client code get when using . Because the producer class is @Dependent (default), the underlying container-managed entity manager reference will not be shared by any other CDI proxies produced. Every time another request want the entity manager, a new instance of the producer class will be instantiated and a new entity manager reference will be injected into the producer which in turn is wrapped in a new CDI proxy.\n\nTo be technically correct, the underlying and unnamed container who do the resource injection into the field  is allowed to reuse old entity managers (see footnote in JPA 2.1 specification, section &quot;7.9.1 Container Responsibilities&quot;, page 357). But so far, we honor the programming model required by JPA.\n\nIn the preceding example, it would not matter if you mark  @Dependent or @RequestScoped. Using @Dependent is semantically more correct. But if you put a wider scope than request scope on the producer class you risk exposing the underlying entity manager reference to many threads which we both know is not a good thing to do. The underlying entity manager implementation is probably a thread-local object, but portable applications cannot rely on implementation details.\n\nCDI does not know how to close whatever stuff it is that you put into the request bound context. More so than anything else, a container-managed entity manager must not be closed by application code.\n\nJPA 2.1, section &quot;7.9.1 Container Responsibilities&quot;:\n\n\n  The container must throw the IllegalStateException if the application\n  calls EntityManager.close on a container-managed entity manager.\n\n\nUnfortunately, many people do use a  method to close the container-managed entity manager. Who can blame them when the official Java EE 7 tutorial provided by Oracle as well as the CDI specification itself use a disposer to close a container-managed entity manager. This is simply wrong and the call to  will throw a  no matter where you put that call, in a disposer method or somewhere else. The Oracle example is the biggest sinner of the two by declaring the producer class to be a . As we learned, this risk exposing the underlying entity manager reference to many different threads.\n\nIt has been proven here that by using CDI producers and disposers wrongfully, 1) the not thread-safe entity manager may be leaked to many threads and 2) the disposer has no effect; leaving the entity manager open. What happened was the IllegalStateException which the container swallowed leaving no trace of it (a mysterious log entry is made which says there was an &quot;error destroying an instance&quot;).\n\nGenerally, using CDI to lookup container-managed entity managers is not a good idea. The application is most likely better off just using  and be happy with it. But there are always exceptions to the rule like in your example, and CDI can also be useful to abstract away the  when handling the life cycle of application-managed entity managers.\n\nTo get a complete picture on how to obtain a container-managed entity manager and how to use CDI to lookup entity managers, you might want to read this and this.\n",
        "excerpt": " a <span class=\"highlight\">IllegalStateException</span> no matter where you put that <span class=\"highlight\">call</span>, in a disposer method or somewhere else. The Oracle example is the biggest sinner of the two by declaring the producer class &hellip; You&#39;re almost right on with your CDI producer. Only thing is that you <span class=\"highlight\">should</span> use a producer method instead of a producer field.\n\nIf you&#39;re using Weld as CDI container (GlassFish 4.1 and WildFly 8.2.0 &hellip; ",
        "title": "Getting a reference to EntityManager in Java EE applications using CDI"
    }, {
        "tags": ["android", "android-recyclerview"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 37456502,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1464255570,
        "creation_date": 1464254126,
        "body": "I am working on a project where user adds data at runtime.I am using cursorloader to load the data content provider to add data to database and customadapter to set the data to recyclerview.The problem is whenever user inserts new data the data is adding to the database but it is not updating in the recyclerview.\n\nMethod  executes when user enters data\n\n\n\nCustom Cursor Adapter:\n\n\n\nAdapter class\n\n\n\nContent Provider :\n\n\n\nThank you\n",
        "excerpt": " cursor);\n\n    @Override\n    public void onBindViewHolder(VH viewHolder, int position) {\n        if (!mDataValid) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor &hellip;  is valid&quot;);\n        }\n        if (!mCursor.moveToPosition(position)) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;couldn&#39;t move cursor to position &quot; + position);\n        }\n        onBindViewHolder &hellip; ",
        "title": "Item in recyclerview is not updating after the data is updated in Database"
    }, {
        "tags": ["java", "android", "android-arrayadapter"],
        "question_score": -1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 2,
        "is_answered": false,
        "question_id": 37295963,
        "item_type": "question",
        "score": -1,
        "last_activity_date": 1463578886,
        "creation_date": 1463564872,
        "body": "Good morning everyone. In order to have an autocompletion editText that can find a character sequence between parentheses or brackets I followed this AutoCompleteTextView not completing words inside parentheses but the CustomArrayAdapter I&#39;ve created made a NoClassDefFoundError :\n\n\n\nI can&#39;t understand why I get this error and how to resolve it, can someone help me please ? \n\nEDIT : The code of the CustomArrayAdapter is the same as here but I changed one class :\n\n\n\nEDIT 2 : As requested here how I create the CustomArrayAdapter object : \n\n\n\nCustomArrayAdapter.java :\n\n\n\nThe path of the 2 files : \n\n\n",
        "excerpt": " {\n/**\n * Lock used to modify the content of {@link #mObjects}. Any write operation\n * performed on the array <span class=\"highlight\">should</span> be synchronized on this lock. This lock is also\n * used by the filter (see {@link #getFilter &hellip;  contain the\n * identifier that matches the one defined in the resource file.\n */\nprivate int mFieldId = 0;\n\n/**\n * Indicates whether or not {@link #notifyDataSetChanged()} must be <span class=\"highlight\">called</span> whenever\n * {@link &hellip; ",
        "title": "NoClassDefFoundError on custom ArrayAdapter"
    }, {
        "tags": ["android", "android-fragments"],
        "question_score": 348,
        "is_accepted": false,
        "answer_id": 30867846,
        "is_answered": false,
        "question_id": 9245408,
        "item_type": "answer",
        "score": 12,
        "last_activity_date": 1462625175,
        "creation_date": 1434458366,
        "body": "While @yydl gives a compelling reason on why the  method is better:\n\n\n  If Android decides to recreate your Fragment later, it&#39;s going to call\n  the no-argument constructor of your fragment. So overloading the\n  constructor is not a solution.\n\n\nit&#39;s still quite possible to use a constructor. To see why this is, first we need to see why the above workaround is used by Android.\n\nBefore a fragment can be used, an instance of a (child class) of  is needed. Hence, android calls , with NO ARGUMENTS. Any overloaded constructor will be ignored.\n\nIn the lifetime of an Activity the fragment gets created as above and destroyed multiple times by Android.\n\nThis however means that if you put data in Fragment object itself, you&#39;ll lose once this Fragment is destroyed.\n\nTo workaround, android asks that you store data using a Bundle, which can then be referenced by your Fragment, which inlcudes . Argument s are protected by Android, and hence are guaranteed to be persistent.\n\nOne way to set this bundle is by using a static  method.\n\nHowever, if you use a constructor:\n\n\n\nthis is exactly same as using\n\n\n\nSo this is doing the exact same thing.\n\nYou can use either, but Android recommends the first, as conceptually, you&#39;re hacking the constructor overloader.\n\nWarning: Naturally, this would fail:\n\n\n\nAs further explaination, here&#39;s Android&#39;s Fragment Class:\n\n\n\nNote that Android asks that the arguments be set only at construction, and guarantees that these will be retained.\n\nEDIT: As pointed out in the comments, Android doesn&#39;t allow using a constructor for this purpose anymore, the above workaround being the reason.\n",
        "excerpt": "\n     * be <span class=\"highlight\">called</span> before the fragment has been attached to its activity; that\n     * is, you <span class=\"highlight\">should</span> <span class=\"highlight\">call</span> it immediately after constructing the fragment.  The\n     * arguments supplied here will be retained across &hellip; While @yydl gives a compelling reason on why the newInstance method is better:\n\n\n  If Android decides to recreate your Fragment later, it&#39;s going to <span class=\"highlight\">call</span>\n  the no-argument constructor of your &hellip; ",
        "title": "Best practice for instantiating a new Android Fragment"
    }, {
        "tags": ["java", "android", "nullpointerexception", "recyclerview", "android-recyclerview"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 36814720,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1461474686,
        "creation_date": 1461435688,
        "body": "So I have a recyclerView inside a swipeToRefreshLayout such as the one defined below:\n\n\n\nThe CustomLinearLayoutManager class is as defined below:\n\n\n\n}\n\nAll of these happen inside a fragment (with viewPager). \nI keep getting the following exceptions in some devices:\n\n\n\nI am not sure why that is. The app is live in Google play and it seems this happens to users who are using version 4.2.2 and version 6 and above. Can anyone point me in the right direction as to how to fix this? I myself am not able to reproduce this issue in my device.\n\nThanks in advance for the help!\n\nEDIT: jeez guys I know what NPE is and how to fix it. I have reviewed my code and it is working fine in most of the devices. So all those people marking this as duplicate: What I wanted to know was I am facing this issue since using REcyclerView and This exception usually happens when LayoutManager is not defined for REcyclerView. But I have defined it and I am still getting the exception. Am I doing something wrong? Is this because of using fragments? Why is this happening to devices above 6 and 4.4.2 devices? \n",
        "excerpt": " happens after &quot;onMeasure&quot; method. As a workaround let&#39;s clear the\n    // recycler now (it <span class=\"highlight\">should</span> not cause any performance issues while scrolling as &quot;onMeasure&quot; is never\n    // <span class=\"highlight\">called</span> whiles scrolling &hellip; \n    makeInsetsDirty(p);\n    // this method <span class=\"highlight\">should</span> be <span class=\"highlight\">called</span> before any getXxxDecorationXxx() methods\n    calculateItemDecorationsForChild(child, tmpRect);\n\n    final int hDecoration &hellip; ",
        "title": "RecyclerView with swipeToRefreshLayout inside fragment"
    }, {
        "tags": ["java", "singleinstance"],
        "question_score": 66,
        "is_accepted": false,
        "answer_id": 36772436,
        "is_answered": false,
        "question_id": 177189,
        "item_type": "answer",
        "score": -1,
        "last_activity_date": 1461389677,
        "creation_date": 1461248361,
        "body": "EDIT: I would like to know why this was downvoted. It&#39;s the best solution I have seen so far. E.g. the server socket approach fails if another application happens to already be listening to the port.\n\nJust download Microsoft Windows Sysinternals TCPView (or use netstat), start it, sort by &quot;State&quot;, look for the line block that says &quot;LISTENING&quot;, pick one whose remote address says your computer&#39;s name, put that port into your new-Socket()-solution. In my implementation of it, I can produce failure every time. And it&#39;s logical, because it&#39;s the very foundation of the approach. Or what am I not getting regarding how to implement this?\n\nPlease inform me if and how I am wrong about this!\n\nMy view - which I am asking you to disprove if possible - is that developers are being advised to use an approach in production code that will fail in at least 1 of about 60000 cases. And if this view happens to be correct, then it can absolutely not be that a solution presented that does not have this problem is downvoted and criticized for its amount of code.\n\nDisadvantages of the socket approach in comparison:\n\n\nFails if the wrong lottery ticket (port number) is chosen.\nFails in multi user environment: Only one user can run the application at the same time. (My approach would have to be slightly changed to create the file(s) in the user tree, but that&#39;s trivial.)\nFails if firewall rules are too strict.\nMakes suspicious users (which I did meet in the wild) wonder what shenanigans you&#39;re up to when your text editor is claiming a server socket.\n\n\n\n\nI just had a nice idea for how to solve the new-instance-to-existing-instance Java communication problem in a way that should work on every system. So, I whipped up this class in about two hours. Works like a charm :D\n\nIt&#39;s based on Robert&#39;s file lock approach (also on this page), which I have used ever since. To tell the already running instance that another instance tried to start (but didn&#39;t) ... a file is created and immediately deleted, and the first instance uses the WatchService to detect this folder content change. I can&#39;t believe that apparently this is a new idea, given how fundamental the problem is.\n\nThis can easily be changed to just create and not delete the file, and then information can be put into it that the proper instance can evaluate, e.g. the command line arguments - and the proper instance can then perform the deletion. Personally, I only needed to know when to restore my application&#39;s window and send it to front.\n\nExample use:\n\n\n\nHere&#39;s the class:\n\n\n",
        "excerpt": "-instance-to-existing-instance Java communication problem in a way that <span class=\"highlight\">should</span> work on every system. So, I whipped up this class in about two hours. Works like a charm :D\n\nIt&#39;s based on Robert&#39;s file &hellip;  situation is apt: This method could be <span class=\"highlight\">called</span> at *any* time.\n    System.err.println(&quot;Deiconified because other instance tried to start.&quot;);\n}\n\n\nHere&#39;s the class:\n\npackage yourpackagehere;\n\nimport &hellip; ",
        "title": "How to implement a single instance Java application?"
    }, {
        "tags": ["android", "database", "sqlite", "sqlite3"],
        "question_score": 489,
        "is_accepted": false,
        "answer_id": 19996964,
        "is_answered": false,
        "question_id": 2493331,
        "item_type": "answer",
        "score": 122,
        "last_activity_date": 1461182281,
        "creation_date": 1384505411,
        "body": "Concurrent Database Access\n\nSame article on my blog(I like formatting more)\n\nI wrote small article which describe how to make access to your android database thread safe.\n\n\n\nAssuming you have your own SQLiteOpenHelper.\n\n\n\nNow you want to write data to database in separate threads.\n\n\n\nYou will get following message in your logcat and one of your changes will not be written.\n\n\n\nThis is happening because every time you create new SQLiteOpenHelper object you are actually making new database connection. If you try to write to the database from actual distinct connections at the same time, one will fail. (from answer above)\n\nTo use database with multiple threads we need to make sure we are using one database connection.\n\nLet’s make singleton class Database Manager which will hold and return single SQLiteOpenHelper object.\n\n\n\nUpdated code which write data to database in separate threads will look like this.\n\n\n\nThis will bring you another crash.\n\n\n\nSince we are using only one database connection, method getDatabase() return same instance of SQLiteDatabase object for Thread1 and Thread2. What is happening, Thread1 may close database, while Thread2 is still using it. That’s why we have IllegalStateException crash.\n\nWe need to make sure no-one is using database and only then close it. Some folks on stackoveflow recommended to never close your SQLiteDatabase. It not only sounds stupid but also honor you with following logcat message.\n\n\n\nWorking sample\n\n\n\nUse it as follows.\n\n\n\nEvery time you need database you should call openDatabase() method of DatabaseManager class. Inside this method, we have a counter, which indicate how many times database is opened. If it equals to one, it means we need to create new database connection, if not, database connection is already created. \n\nThe same happens in closeDatabase() method. Every time we call this method, counter is decreased, whenever it goes to zero, we are closing database connection.\n\n\n\nNow you should be able to use your database and be sure it&#39;s thread safe.\n",
        "excerpt": "() {\n        if (instance == null) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(DatabaseManager.class.getSimpleName() +\n                    &quot; is not initialized, <span class=\"highlight\">call</span> initialize(..) method first &hellip;  database you <span class=\"highlight\">should</span> <span class=\"highlight\">call</span> openDatabase() method of DatabaseManager class. Inside this method, we have a counter, which indicate how many times database is opened. If it equals to one, it means we need &hellip; ",
        "title": "What are the best practices for SQLite on Android?"
    }, {
        "tags": ["android", "android-fragments", "android-support-library"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 36656077,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1460751256,
        "creation_date": 1460751256,
        "body": "When using MultiSelectListPreference with PreferenceFragmentCompat, like all preference with dialogs, we need to use a DialogFragment to show the preference interface and capture the input.  The support library provides just such a dialog fragment: MultiSelectListPreferenceDialogFragment\n\nHowever, this inherits from android.support.v14.preference.PreferenceDialogFragment which inherits from android.app.DialogFragment.  In other words, it cannot be shown with the SupportFragmentManager, effectively making it impossible to use the MultiSelectList preference if your app is designed around the support libraries.\n\nLuckily, there is no reason I could find for this, so a workaround is to just copy&#39;n&#39;paste the google code from MultiSelectListPreferenceDialogFragment and PreferenceDialogFragment and change the inheritance to extend android.support.v4.app.DialogFragment.\n\nI filed a bug with google (here) and the code is below.  I was using com.android.support:preference-v14:23.3.0\n\nThis works fine for my project, but I don&#39;t understand the logic behind limiting the use of these support preferences to non-support centric apps.  I understand it is in the v14 support library, but other support libraries require the SupportFragmentManager, etc. and all the docs recommend using the support libraries.  Is there a better way to go about this?\n\nMultiSelectPrefenceDialog (replaces MultiSelectListPreferenceDialogFragment)\n\n\n\nCalling dialog fragment in PreferenceFragmentCompat\n\n\n",
        "excerpt": " MultiSelectListPreference preference = getListPreference();\n            if (preference.getEntries() == null || preference.getEntryValues() == null) {\n                throw new <span class=\"highlight\">IllegalStateException</span> &hellip; (savedInstanceState);\n        final Fragment rawFragment = getTargetFragment();\n        if (!(rawFragment instanceof DialogPreference.TargetFragment)) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;Target &hellip; ",
        "title": "MultiSelectListPreferenceDialogFragment cannot be shown with SupportFragmentManager"
    }, {
        "tags": ["android", "android-layout", "android-fragments", "android-preferences"],
        "question_score": 1,
        "is_accepted": true,
        "answer_id": 36533519,
        "is_answered": false,
        "question_id": 34496529,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1460311991,
        "creation_date": 1460311659,
        "body": "There is a much better solution. \n\nFirst I use the a PreferenceFragment that is fit for the support library. Author Christophe Beyls (thank you!).\n\nStep 1: Base class: PreferenceFragment for the support library \n\n\n\nStep 2: Create your own FragmentPreferences based on the above file: \n\nStep 2.1 - Create a layout file: res/layout/preferences_with_toolbar.xml\n\n\n\nStep 2.2 - Create the menu options in the toolbar. None in my case. \n\n\n\nStep 2.3 - Create your FragmentPreferences\n\n\n",
        "excerpt": ");\n    }\n\n    private void requirePreferenceManager() {\n        if (this.mPreferenceManager == null) {\n            throw new RuntimeException(&quot;This <span class=\"highlight\">should</span> be <span class=\"highlight\">called</span> after super.onCreate &hellip; ();\n        if (root == null) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;Content view not yet created&quot;);\n        }\n        View rawListView = root.findViewById(android.R.id.list &hellip; ",
        "title": "Preferencefragment as DialogFragment needs a toolbar (compliant with design library)"
    }, {
        "tags": ["android", "sqlite", "cursor", "android-recyclerview", "ormlite"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 36473704,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1460025999,
        "creation_date": 1460025548,
        "body": "Hello i want to do pagination using sqlite database,I am able to get results in sets of 100 rows/query. I am using cursor adapter here. Data is getting replaced instead of getting appended. Below is my Cursor Adapter for recyclerview \n\n\n\n}\n\nany suggestion what must be going wrong?\n",
        "excerpt": ", Cursor cursor);\n\n@Override\npublic void onBindViewHolder(VH viewHolder, int position) {\n    if (!mDataValid) {\n        throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor is valid &hellip; &quot;);\n    }\n    if (!mCursor.moveToPosition(position)) {\n        throw new <span class=\"highlight\">IllegalStateException</span>(&quot;couldn&#39;t move cursor to position &quot; + position);\n    }\n    onBindViewHolder(viewHolder, mCursor &hellip; ",
        "title": "Pagination in recyclerview using cursor adapter"
    }, {
        "tags": ["android", "sqlite", "android-layout", "recyclerview"],
        "question_score": 3,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 36173919,
        "item_type": "question",
        "score": 3,
        "last_activity_date": 1459229722,
        "creation_date": 1458724345,
        "body": "I am using AsyncTask to load data from a SQLite Database and then providing data to a Recycler View using a StaggeredLayoutManager and CustomListAdapter.\n\nIf I don&#39;t close the cursor of doInBackground method in the onPostExecuteMethod, the transition from the previous activity is laggy, and android logcat says &quot;Skipped 52 frames&quot;.\n\nIf I do close the cursor, at the end of the Post Execute method, the lag doesn&#39;t occur, but nothing is rendered inside the Activity. (Recycler View renders nothing.)\n\n\n\ndoInBackground method\n\n\n\nThe BaseAdapter class\n\n\n\nThe extended Adapter class\n\n\n",
        "excerpt": " cursor);\n\n    @Override\n    public void onBindViewHolder(VH viewHolder, int position) {\n        if (!mDataValid) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;this <span class=\"highlight\">should</span> only be <span class=\"highlight\">called</span> when the cursor &hellip;  is valid&quot;);\n        }\n        if (!mCursor.moveToPosition(position)) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;couldn&#39;t move cursor to position &quot; + position);\n        }\n        onBindViewHolder &hellip; ",
        "title": "Closing cursor in onPostExecute renders nothing"
    }, {
        "tags": ["java", "android", "android-lifecycle"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 36116966,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1458502351,
        "creation_date": 1458494613,
        "body": "I&#39;m struggling with an Android activity lifecycle issue: When I return to an activity from its child activity, all the instance variables are null, even though they should have been initialized in the onCreate() method of the activity. As you can see below, the SignSearchActivity works fine as long as I stay on the activity. Orientation changes are no problem. As soon as I navigate to the child activity SignSearch_Video_Activity and navigate back up again, a NullPointerException is thrown in the SignSearchActivity.onStart() method. As you can see from the log output the SignSearchActivity.onCreate() method is actually called before the onStart() method. I&#39;ve had a very similar issue in the SignSearchActivity.onPostExecute() method, but I was able to find a workaround for that (see FIXME code below). Now, I&#39;m really stuck.\n\nAny help very much appreciated.\n\nBest\n\nMatthias\n\nSearching for a string triggers normal lifecycle flow (instance hashCode at the end)\n\n\n\nOrientation change will saveInstance and create a new instance of SignSearchActivity (see hashCode at the end)\n\n\n\nClicking on a sign will also saveInstance\n\n\n\nClicking on homeAsUpIndicator will cause NullPointerException in SignSearchActitivity\n\n\n\nSignSearchActivity\n\n\n\nSignSearch_Video_Activity \n\n\n",
        "excerpt": "I&#39;m struggling with an Android activity lifecycle issue: When I return to an activity from its child activity, all the instance variables are null, even though they <span class=\"highlight\">should</span> have been initialized &hellip;  the SignSearchActivity.onCreate() method is actually <span class=\"highlight\">called</span> before the onStart() method. I&#39;ve had a very similar issue in the SignSearchActivity.onPostExecute() method, but I was able to find a workaround for that (see FIXME &hellip; ",
        "title": "Activity instance fields null after returning from child activity"
    }, {
        "tags": ["android"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 36092681,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1458329191,
        "creation_date": 1458328900,
        "body": "i currently have a working project that uses fragment to select layouts from the list , how ever what am trying to do now is add 1 class and layout fragfrant from a different project and am getting this error.\n\nandroid.support.v4.app.Fragment; when i high light the line.\n\n\n\ni get the error on  case 114 KaabaLocatorFragment()\nwhen i highlight this line it says\n\nrequired  android.support.v4.app.Fragment\nfound it.bellotti.navigationdrawer.compass.KaabaLocatorFragment\n\nalso the case 114 is new line i just added to this project , i wanted to just ad a compass layout and class to this project so here is the line am having problem\nhere is  kaabalocatorFragment\n\n\n",
        "excerpt": "() {\n    if (!PermissionUtil.hasSelfPermission(getActivity(), Manifest.permission.WRITE_EXTERNAL_STORAGE)) {\n      throw new <span class=\"highlight\">IllegalStateException</span>(&quot;WRITE_EXTERNAL_STORAGE permission <span class=\"highlight\">should</span> be granted before &hellip;  for accessibility */\n                R.string.app_name /* nav drawer close - description for accessibility */\n        );\n//        {\n//\n//            /** <span class=\"highlight\">Called</span> when a drawer has settled in a completely &hellip; ",
        "title": "android fragment android.support.v4.app.Fragment; error"
    }, {
        "tags": ["android", "google-play-services", "google-play-games"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 36050467,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1458225172,
        "creation_date": 1458180832,
        "body": "I am creating a game using the API of Google Play Games. I have read the documentation on the leaderboards. I have used the same code to update the user&#39;s score, but it always returns the code . I&#39;ve used the logcat to display the results of the call:\n\n\n\nHere is the code:\n\n\n\nGameHelperClass:\n\n\n\nI&#39;ve tried to change the score, but there is nothing, I have also checked that the leaderboard is set up correctly.\n",
        "excerpt": " <span class=\"highlight\">IllegalStateException</span>(error);\n        }\n    }\n\n    private void doApiOptionsPreCheck() {\n        if (mGoogleApiClientBuilder != null) {\n            String error = &quot;GameHelper: you cannot <span class=\"highlight\">call</span> set*ApiOptions after &hellip;  listener) {\n        if (mSetupDone) {\n            String error = &quot;GameHelper: you cannot <span class=\"highlight\">call</span> GameHelper.setup() more than once!&quot;;\n            logError(error);\n            throw new <span class=\"highlight\">IllegalStateException</span> &hellip; ",
        "title": "Google Play Games API returns RESULT_RECONNECT_REQUIRED when submit user score"
    }, {
        "tags": ["android", "android-fragments", "asynchronous", "android-asynctask", "android-lifecycle"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": false,
        "question_id": 28683276,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1458146915,
        "creation_date": 1424724990,
        "body": "Using a retained fragment to host asynchronous tasks is not a new idea (see Alex Lockwood&#39;s excellent blog post on the topic)\n\nBut after using this I&#39;ve come up against issues when delivering content back to my activity from the AsyncTask callbacks. Specifically, I found that trying to dismiss a dialog could result in an IllegalStateException. Again, an explanation for this can be found in another blog post by Alex Lockwood. Specifically, this section explains what is going on:\n\n\n  Avoid performing transactions inside asynchronous callback methods.\n  \n  This includes commonly used methods such as AsyncTask#onPostExecute()\n  and LoaderManager.LoaderCallbacks#onLoadFinished(). The problem with\n  performing transactions in these methods is that they have no\n  knowledge of the current state of the Activity lifecycle when they are\n  called. For example, consider the following sequence of events:\n  \n  \n  An activity executes an AsyncTask.\n  The user presses the &quot;Home&quot; key,\n  causing the activity&#39;s onSaveInstanceState() and onStop() methods to\n  be called.\n  The AsyncTask completes and onPostExecute() is called,\n  unaware that the Activity has since been stopped.\n  A FragmentTransaction is committed inside the onPostExecute() method,\n  causing an exception to be thrown.\n  \n\n\nHowever, it seems to me that this is part of a wider problem, it just happens that the fragment manager throws an exception to make you aware of it. In general, any change you make to the UI after  will be lost. So the advice\n\n\n  Avoid performing transactions inside asynchronous callback methods.\n\n\nActually should be:\n\n\n  Avoid performing UI updates inside asynchronous callback methods.\n\n\nQuestions:\n\n\nIf using this pattern, should you therefore cancel your task, preventing callbacks in  if not rotating?\n\n\nLike so:\n\n\n\n\nShould you even bother using retained fragments at all for retaining ongoing tasks? Will it be more effective to always mark something in your model about an ongoing request? Or do something like RoboSpice where you can re-connect to an ongoing task if it is pending. To get a similar behaviour to the retained fragment, you&#39;d have to cancel a task if you were stopping for reasons other than a config change.\nContinuing from the first question: Even during a config change, you should not be making any UI updates after  so should you actually do something like this:\n\n\nRough code:\n\n\n\nThe  would do something like the PauseHandler seen here\n",
        "excerpt": " back to my activity from the AsyncTask callbacks. Specifically, I found that trying to dismiss a dialog could result in an <span class=\"highlight\">IllegalStateException</span>. Again, an explanation for this can be found &hellip;  of the Activity lifecycle when they are\n  <span class=\"highlight\">called</span>. For example, consider the following sequence of events:\n  \n  \n  An activity executes an AsyncTask.\n  The user presses the &quot;Home&quot; key,\n  causing &hellip; ",
        "title": "How to deliver and persist changes to the UI from an asynchronous task hosted by a retained fragment?"
    }, {
        "tags": ["android", "android-fragments"],
        "question_score": 0,
        "is_accepted": true,
        "answer_id": 35912020,
        "is_answered": false,
        "question_id": 35911739,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1457601115,
        "creation_date": 1457601115,
        "body": "You can call it more than once or twice IF a  is not attached to any .\n\nThe code below is copied from \n\n\n\nYou can call the method as long as you want IF not attached to the activity\n",
        "excerpt": ".  This can only\n * be <span class=\"highlight\">called</span> before the fragment has been attached to its activity; that\n * is, you <span class=\"highlight\">should</span> <span class=\"highlight\">call</span> it immediately after constructing the fragment.  The\n * arguments supplied here &hellip;  will be retained across fragment destroy and\n * creation.\n */\n public void setArguments(Bundle args) {\n        if (mIndex &gt;= 0) {\n            throw new <span class=\"highlight\">IllegalStateException</span>(&quot;Fragment already active&quot;);\n        }\n        mArguments = args;\n }\n\n\nYou can <span class=\"highlight\">call</span> the method as long as you want IF not attached to the activity\n &hellip; ",
        "title": "can we call twice setArgument() on the Fragment?"
    }, {
        "tags": ["java", "android", "android-recyclerview", "onmeasure"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 35620507,
        "is_answered": false,
        "question_id": 35619673,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1456383809,
        "creation_date": 1456383809,
        "body": "Use this custom linear layout manager.. just assign it to your recycler view and you can use WRAP_CONTENT in XML...\n\n\n\n}\n",
        "excerpt": " the\n    // recycler now (it <span class=\"highlight\">should</span> not cause any performance issues while scrolling as &quot;onMeasure&quot; is never\n    // <span class=\"highlight\">called</span> whiles scrolling)\n    recycler.clear();\n\n    final int stateItemCount = state.getItemCount &hellip;  vMargin = p.topMargin + p.bottomMargin;\n\n    // we must make insets dirty in order calculateItemDecorationsForChild to work\n    makeInsetsDirty(p);\n    // this method <span class=\"highlight\">should</span> be <span class=\"highlight\">called</span> before any &hellip; ",
        "title": "Getting Total Height of RecyclerView"
    }, {
        "tags": ["android", "recyclerview", "gridlayoutmanager"],
        "question_score": 1,
        "is_accepted": true,
        "answer_id": 35478700,
        "is_answered": false,
        "question_id": 35478570,
        "item_type": "answer",
        "score": 1,
        "last_activity_date": 1455790871,
        "creation_date": 1455790871,
        "body": "Please go through this i have made it custom as per my requirement :\n\nDO some tweaks for your requirement \n\n\n",
        "excerpt": "\n        makeInsetsDirty(p);\n        // this method <span class=\"highlight\">should</span> be <span class=\"highlight\">called</span> before any getXxxDecorationXxx() methods\n        calculateItemDecorationsForChild(child, tmpRect);\n\n        final int hDecoration &hellip; );\n        if (this.view == null) throw new <span class=\"highlight\">IllegalStateException</span>(&quot;view == null&quot;);\n        this.overScrollMode = overScrollMode;\n        ViewCompat.setOverScrollMode(view, overScrollMode);\n    }\n\n    public static &hellip; ",
        "title": "Recyclerview with GridLayout Manager inside another recycerview"
    }, {
        "tags": ["java", "android", "google-signin", "googlesigninapi"],
        "question_score": 1,
        "is_accepted": false,
        "answer_id": 35445678,
        "is_answered": false,
        "question_id": 35332835,
        "item_type": "answer",
        "score": 1,
        "last_activity_date": 1455770023,
        "creation_date": 1455668820,
        "body": "First of all, you should not get IllegalStateException unless you call opr.get() before isDone() or call it multiple times (no matter it&#39;s a failure or success result):\nhttps://developers.google.com/android/reference/com/google/android/gms/common/api/OptionalPendingResult.html#get()\nCould you double check your code / paste your exact code here?\n\nSecondly, the most common issue for INTERNAL_ERROR is missing the right OAuth2 client registration. (Unfortunately, for now, the status code is INTERNAL_ERROR 8, which is not helpful.) E.g. Take a look at this thread:\nOccured an `INTERNAL_ERROR` when requestEmail from GoogleSignInOptions Android. Since you already added the Wallet scope, if missing OAuth2 registration,  you will see &quot;unregistered Android application&quot; in the consent dialog. (I attached a screenshot at the end)\n\nThirdly, you can save a lot of boiler plate code by using enableAutoManage. Please check out the official doc:\nhttps://developers.google.com/identity/sign-in/android/sign-in\n(e.g. all those error handling in your onConnectionFailed handler, connect() / disconnect() will both be called automatically). And it&#39;s okay to call Auth.GoogleSignInApi.silentSignIn() in your onActivityResult. But a simpler way to get the result is:\n\n\n\n\n",
        "excerpt": "First of all, you <span class=\"highlight\">should</span> not get <span class=\"highlight\">IllegalStateException</span> unless you <span class=\"highlight\">call</span> opr.get() before isDone() or <span class=\"highlight\">call</span> it multiple times (no matter it&#39;s a failure or success result):\nhttps://developers.google.com &hellip; /sign-in\n(e.g. all those error handling in your onConnectionFailed handler, connect() / disconnect() will both be <span class=\"highlight\">called</span> automatically). And it&#39;s okay to <span class=\"highlight\">call</span> Auth.GoogleSignInApi.silentSignIn() in your &hellip; ",
        "title": "OptionalPendingResult&lt;GoogleSignInResult&gt; is always throwing IllegalStateException with cause &quot;Result has already been consumed&quot;"
    }, {
        "tags": ["android", "android-actionbar", "android-5.0-lollipop"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 35372858,
        "is_answered": false,
        "question_id": 35372726,
        "item_type": "answer",
        "score": 1,
        "last_activity_date": 1455314227,
        "creation_date": 1455314227,
        "body": "The  does not inherit from  so you&#39;ll need to modify it if you want similar behavior. In one of my applications I created my own  here is the code:\n\n\n\nMost of the code was borrowed from the  implementation which is why you&#39;ll see commented out  and  methods.\n",
        "excerpt": ";\n        mStandardEmptyView = null;\n        super.onDestroy();\n    }\n\n    /**\n     * This method will be <span class=\"highlight\">called</span> when an item in the list is selected.\n     * Subclasses <span class=\"highlight\">should</span> override. Subclasses can <span class=\"highlight\">call</span> &hellip;  to supply the text it <span class=\"highlight\">should</span> use.\n     */\n    public void setEmptyText(CharSequence text) {\n        ensureList();\n        if (mStandardEmptyView == null) {\n            throw new <span class=\"highlight\">IllegalStateException</span> &hellip; ",
        "title": "Unable to change ActionBar background in ListActivity"
    }],
    "name": "IllegalStateException Should not be called"
}, {
    "items": [{
        "tags": ["java", "spring", "maven", "jpa", "aspectj"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38200747,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468670040,
        "creation_date": 1467713576,
        "body": "I am trying aspectj with EntityManager, its giving error\n\n\n\nPOM:    \n\n\n\nDriver application:\n\n\n\nService class:\n\n\n\nAspect:\n\n\n\napplication.properties:\n\n\n\nNeed to know where am doing wrong??\n",
        "excerpt": ");\n            service.save();\n\n        } catch (<span class=\"highlight\">RuntimeException</span> e) {\n            System.out.println(&quot;Caught runtime <span class=\"highlight\">exception</span>&quot;);\n        }\n    }\n}\n\n\nService class:\n\n@Component\npublic class Service &hellip; ",
        "title": "EntityManager with aspectj is not working"
    }, {
        "tags": ["php", "amazon-web-services", "ses"],
        "question_score": 2,
        "is_accepted": false,
        "answer_id": 38409398,
        "is_answered": false,
        "question_id": 38225288,
        "item_type": "answer",
        "score": 0,
        "last_activity_date": 1468659769,
        "creation_date": 1468658927,
        "body": "Class MessageRejectedException Indicates that the action failed, and the message could not be sent. Check the error stack for more information about what caused the error.\n\n\n\nTry this -&gt; use Aws\\Ses\\Exception\\MessageRejectedException;\nor use Aws\\Ses\\Exception\\SesException; and replace class name into catche block\n\nBcause Aws\\Ses\\Exception is namespace of class MessageRejectedException.\nyou have to use class with namespace ,not only namespace.\n\n\n\nI hope helped.\nGood luck\n",
        "excerpt": " by <span class=\"highlight\">RuntimeException</span>\n        Extended by Aws\\Common\\<span class=\"highlight\">Exception</span>\\<span class=\"highlight\">RuntimeException</span> implements Aws\\Common\\<span class=\"highlight\">Exception</span>\\AwsExceptionInterface\n            Extended by Aws\\Common\\<span class=\"highlight\">Exception</span>\\ServiceResponseException &hellip; Class MessageRejectedException Indicates that the action failed, and the message could not be sent. Check the error stack for more information about what caused the error.\n\n<span class=\"highlight\">Exception</span>\n    Extended &hellip; ",
        "title": "Get Error Code For Unverified Identities In SendMail Exception AWS SES PHP SDK"
    }, {
        "tags": ["java", "neo4j", "cypher", "spring-data-neo4j"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38403130,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468636713,
        "creation_date": 1468608170,
        "body": "I have uploaded a CSV file and already have nodes and relationship defined on Neo4j. I&#39;ve tried to create a program base on an example that basically run a cypher query from Spring that would generate the output from neo4j. However, I&#39;m encountering this error:\n\n\n\nI&#39;m wondering what could possibly be the error? \nHere is my code:\n\n\n\n}\n",
        "excerpt": " generate the output from neo4j. However, I&#39;m encountering this error:\n\n<span class=\"highlight\">Exception</span> in thread &quot;main&quot; java.lang.NoSuchMethodError:org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(Ljava/io/File &hellip; )-[:APPLIES_TO]-&gt;(e:Time) RETURN b,e&quot;).resultAsString();\n    }\n\n    db.shutdown();\n    }\n}\n\nprivate void clear(){\n    try{\n        deleteRecursively(DB_PATH);\n    }\n    catch(IOException e){\n        throw new <span class=\"highlight\">RuntimeException</span>(e);\n    }\n}\n\n\n}\n &hellip; ",
        "title": "Run a Cypher query from Spring to Neo4j"
    }, {
        "tags": ["java", "intellij-idea"],
        "question_score": 0,
        "is_accepted": false,
        "answer_id": 38402365,
        "is_answered": false,
        "question_id": 38401821,
        "item_type": "answer",
        "score": 2,
        "last_activity_date": 1468606368,
        "creation_date": 1468605094,
        "body": "Thanks to your edit, it&#39;s easier to explain the behavior you&#39;re seeing. IntelliJ flags Exceptions that do not subclass java.lang.RuntimeException because that is an actual compilation error. \n\nLet&#39;s look at the JavaDoc for Exception:\n\n\n  The class Exception and any subclasses that are not also subclasses of RuntimeException are checked exceptions. Checked exceptions need to be declared in a method or constructor&#39;s throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.\n\n\n... And the JavaDoc for RuntimeException:\n\n\n  RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor&#39;s throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.\n\n\nIn other words, you can throw a RuntimeException overtly in your code, and you don&#39;t necessarily have to declare it or catch it, and your compiler will be perfectly happy with that (although your API&#39;s users might not be so jolly). On the other hand, Exceptions that do not subclass RuntimeException are called &quot;checked&quot; exceptions, and must either be declared as thrown by your methods or caught and handled when they might occur, in accordance with the language&#39;s specifications.\n\n(P.S., if you didn&#39;t catch it yet, NullPointerException is a RuntimeException. Hence, it is unchecked.)\n",
        "excerpt": " look at the JavaDoc for <span class=\"highlight\">Exception</span>:\n\n\n  The class <span class=\"highlight\">Exception</span> and any subclasses that are not also subclasses of <span class=\"highlight\">RuntimeException</span> are checked exceptions. Checked exceptions need to be declared &hellip;  for <span class=\"highlight\">RuntimeException</span>:\n\n\n  <span class=\"highlight\">RuntimeException</span> and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor&#39;s throws clause if they can be thrown by the execution &hellip; ",
        "title": "IntelliJ IDEA doesn&#39;t highlight the code which throws an exception - how to turn it on?"
    }, {
        "tags": ["c#", "angularjs", "entity-framework", "asp.net-web-api", "identity"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 32433161,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468596309,
        "creation_date": 1441610460,
        "body": "I want to build a website in Angular with a web service that Android/iOS can use.  I finally found a great tutorial that helped me set that up.  The next step, is to extend the Identity Model.  So, I added a property.  Then I started to get an exception:\n\n&quot;The model backing the &#39;AuthContext&#39; context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269).\n\nSo, when I follow those instructions, I get this:\n\n\n\nI&#39;ve changed my initialiser in Startup ( commented shows what it was )\n\n\n\nand in a static constructor in the context class ( this combination is what i did in another project )\n\n\n\nI am at a loss, I&#39;ve googled, but the solutions I see, don&#39;t seem to work.  VS is running as admin.  I just want EF to not care about my DB, and to trust me that it&#39;s the way it should be....\n\nActually, if I tell it to replace my DB ( which I don&#39;t like ), I get this error:\n\n\n\nThere is no path that just leaves me alone and trusts me to manage my own DB...\n\nThanks\n",
        "excerpt": " = $utilityAssembly.CreateInstance &lt;&lt;&lt;&lt; (\n    + CategoryInfo          : InvalidOperation: (CreateInstance:String) [], <span class=\"highlight\">RuntimeException</span>\n    + FullyQualifiedErrorId : InvokeMethodOnNull\n\n<span class=\"highlight\">Exception</span> calling &hellip;  added a property.  Then I started to get an <span class=\"highlight\">exception</span>:\n\n&quot;The model backing the &#39;AuthContext&#39; context has changed since the database was created. Consider using Code First Migrations to update &hellip; ",
        "title": "EF Identity in WebAPI 2 stops working when model changed"
    }, {
        "tags": ["java", "scala", "io", "inputstream"],
        "question_score": 31,
        "is_accepted": false,
        "answer_id": 38399585,
        "is_answered": false,
        "question_id": 14295099,
        "item_type": "answer",
        "score": 1,
        "last_activity_date": 1468595595,
        "creation_date": 1468595595,
        "body": "Another solution: first create a list of input stream and then create the sequence of input streams:\n\n\n",
        "excerpt": ")\n        .map(f -&gt; {\n            try {\n                return new FileInputStream(f.toString());\n            } catch (<span class=\"highlight\">Exception</span> e) {\n                throw new <span class=\"highlight\">RuntimeException</span>(e);\n            }\n        }).collect(Collectors.toList());\n\nnew SequenceInputStream(Collections.enumeration(iss)))\n\n &hellip; ",
        "title": "How to chain multiple different InputStreams into one InputStream"
    }, {
        "tags": ["spring", "spring-integration", "spring-transactions"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 38399030,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468594829,
        "creation_date": 1468593950,
        "body": "I am breaking my head against the wall since I do not have a clue of why the transactions are not rolling back.\n\nI am using spring integration in my project and my  looks like below:\n\n\n\nMy java file looks like this:\n\n\n\nWhen I post the message on the queue, I see the exception but the message in the queue is consumed. The transaction is not rolling back and the message is not put back in the queue. Please let me know where I am going wrong.\n",
        "excerpt": "\n    public void handleClient(String str){\n        System.out.println(&quot;handleClient&quot;);\n        throw new <span class=\"highlight\">RuntimeException</span>(&quot;Throwing some runtime <span class=\"highlight\">exception</span>....&quot;);\n    }\n\n    public static void main &hellip; (String[] args) {\n        ApplicationContext context = new ClassPathXmlApplicationContext(&quot;applicationContext.xml&quot;);\n    }\n}\n\n\nWhen I post the message on the queue, I see the <span class=\"highlight\">exception</span> but the message &hellip; ",
        "title": "Jms-message-driven channel adaper not rolling back the transaction"
    }, {
        "tags": ["performance", "jsf", "viewhandler"],
        "question_score": 1,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38260262,
        "item_type": "question",
        "score": 1,
        "last_activity_date": 1468487147,
        "creation_date": 1467959500,
        "body": "It seems that it is possible to reuse UIViewRoot object during the restore view phase in JSF as suggested in this link here\n\nI am dealing with a very large form here with hundreds of data elements and on profiling the application, I found that that the RestoreView phase is taking the longest amount of time.\n\nSo following this suggestion, I tried to cache the UIViewRoot object in the session object and it seems to work and increase the performance well.\n\nBut what I need to know is that will it cause any problem (like stale data or any other known issues) with the framework.\n\nIs there any other way of caching the View Root.\n\nEvery time the FullVisitContext is called, it takes a long time and PartialVisitContext is not working for me.\n\nThis is what I have written in the view handler\n\n\n",
        "excerpt": "&quot;, facesException); \n            throw facesException;   \n        } catch (<span class=\"highlight\">Exception</span> e) { \n            loggingService.error(this, &quot;JSF renderView <span class=\"highlight\">exception</span>&quot;, e);  \n            throw new <span class=\"highlight\">RuntimeException</span>(e &hellip; (this, &quot;JSF: restoreView: end&quot;); \n        return cachedView;  \n        } catch (<span class=\"highlight\">Exception</span> e) { \n               loggingService.error(this, &quot;JSF restoreView <span class=\"highlight\">exception</span>&quot;, e);\n               throw new &hellip; ",
        "title": "Reuse UIViewRoot object during the restore view phase"
    }, {
        "tags": ["scala", "plsql", "slick", "anorm"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38271825,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468484234,
        "creation_date": 1467996443,
        "body": "i get this error when i run application on localhost:9000/\n\n[RuntimeException: java.lang.ExceptionInInitializerError]\n\nbelow is the error stack trace:\n\nplay.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.ExceptionInInitializerError]]\n    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)\n    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)\n    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)\n    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)\n    at \n",
        "excerpt": "$1: Execution <span class=\"highlight\">exception</span>[[<span class=\"highlight\">RuntimeException</span>: java.lang.ExceptionInInitializerError]]\n    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280 &hellip; i get this error when i run application on localhost:9000/\n\n[<span class=\"highlight\">RuntimeException</span>: java.lang.ExceptionInInitializerError]\n\nbelow is the error stack trace:\n\nplay.api.http.HttpErrorHandlerExceptions$$anon &hellip; ",
        "title": "Using play2.5 ,hibernate(all latest) ,,I am using PL/SQL from my oracle 12c(for apex 4.2.6),, is it a JDK compatibility error?"
    }, {
        "tags": ["java"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 31619678,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468482825,
        "creation_date": 1437771547,
        "body": "I have this error and I tried many things but I don&#39;t know where the problem is.\n\nI am working with the architecture Jpa/Eclipselink/OpenEJB and I want to test a Class Test JUnit in order to put some recordings in Database.\n\nThe error is\n\n\n  Results :\n  \n  Tests in error: \n   initDB(dao.JUnitInitDBLocal): javax.persistence.PersistenceException: &gt;Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException\n  \n  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0\n  \n  \n  \n  BUILD FAILURE\n  \n  Total time: 1:05.219s\n  Finished at: Fri Jul 24 22:47:36 CEST 2015\n  \n  Final Memory: 6M/15M\n  \n  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-cli) on project mv-pam-openejb-eclipselink: There are test failures.\n  \n  Please refer to C:\\Users\\user\\Documents\\NetBeansProjects\\Chapitre 5\\mv-pam-openejb-eclipselink\\target\\surefire-reports for the individual test results.\n  -&gt; [Help 1]\n  \n  To see the full stack trace of the errors, re-run Maven with the -e switch.\n  Re-run Maven using the -X switch to enable full debug logging.\n\n\nThis is my Class Test : \n\n\n\nThis is my persistence.xml file:\n\n\n\n\n\nThis is my Pom.xml file:\n\n\n\n\n\nI Think the problem is in this three Files cause I tested the others Packages Jpa, Dao, Exception in other architecture and the test passed.\n\nif any one can help me i will be grateful . \n\n\n\nMy Eception Class is : \n\n\n",
        "excerpt": " recordings in Database.\n\nThe error is\n\n\n  Results :\n  \n  Tests in error: \n   initDB(dao.JUnitInitDBLocal): javax.persistence.PersistenceException: &gt;<span class=\"highlight\">Exception</span> [EclipseLink-4002] (Eclipse Persistence &hellip;  : indemniteDao.findAll()) {\n        indemniteDao.destroy(indemnite);\n    }\n\n}\n\n\n @AfterClass\n public static void terminate() throws <span class=\"highlight\">Exception</span> {\n }\n}\n\n\nThis is my persistence.xml file:\n\n&lt;?xml version=&quot;1.0 &hellip; ",
        "title": "javax.persistence.persistenceexception exception eclipselink-4002 (eclipse persistence services - 2.5.2.v 20140319"
    }, {
        "tags": ["java", "exception"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 2,
        "is_answered": true,
        "question_id": 32176702,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468481670,
        "creation_date": 1440401629,
        "body": "I have a DBUtil class for jdbc,  some method like query, insert and update, when   some errors occur, we throw a RuntimeException now, but I have some questions.\n When error occor, if I don&#39;t use try catch block to handle exception, I can&#39;t define whether it was succeed or not in code, so I can&#39;t do other things using the result, and controller will have no response rather than 500 error.\n\n1:\n\n\n\n2:\n\n\n\nso, which is better in code?\nThanks!\n",
        "excerpt": ":\n\ntry{\n\n} catch(<span class=\"highlight\">Exception</span> e){\n    throw new <span class=\"highlight\">RuntimeException</span>(&quot;...&quot;)\n}\n\n\n2:\n\ntry{\n\n} catch(<span class=\"highlight\">Exception</span> e){\n    log.error(&quot;..&quot;)\n    return someresult;// -1, empty list or others\n}\n\n\nso, which is better in code?\nThanks!\n &hellip; I have a DBUtil class for jdbc,  some method like query, insert and update, when   some errors occur, we throw a <span class=\"highlight\">RuntimeException</span> now, but I have some questions.\n When error occor, if I don&#39;t use try &hellip; ",
        "title": "Return error code, msg or throw exception"
    }, {
        "tags": ["php", "silex", "runtimeexception", "doctrine-odm", "doctrine-mongodb"],
        "question_score": 2,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 27750191,
        "item_type": "question",
        "score": 2,
        "last_activity_date": 1468475692,
        "creation_date": 1420242688,
        "body": "I could really use a second pair of eyes. I am attempting to create a custom user provider using Silex&#39;s SecurityServiceProvider in conjunction with Doctrine MongoDB ODM, and I keep receiving the following error when attempting to log in:\n\n\n\nNote: If I hard-code the users, it works perfectly\n\n\n\nAs far as I can tell, I have followed the Silex documentation, which can be found here. I verified that it is successfully fetching the user from the db, so I know that is not the issue. Below is the pertinent code, including snippets from app.php, the user class, and my custom user provider class.\n\n\n\n\n\n\n\n\n\n\n\n\n",
        "excerpt": " the following error when attempting to log in:\n\n<span class=\"highlight\">RuntimeException</span> in ContextListener.php line 177:\nThere is no user provider for user &quot;FooBar\\Document\\User&quot;.\n\n\nNote: If I hard-code the users, it works &hellip; \\Core\\<span class=\"highlight\">Exception</span>\\UsernameNotFoundException;\nuse Symfony\\Component\\Security\\Core\\<span class=\"highlight\">Exception</span>\\UnsupportedUserException;\n\nclass UserRepository implements UserProviderInterface\n{\n    public function &hellip; ",
        "title": "How to get a Custom User Provider working in Silex?"
    }],
    "name": "RuntimeException Exception"
}, {
    "items": [{
        "tags": ["android", "xml", "exception", "android-studio", "gradle"],
        "question_score": 12,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 4,
        "is_answered": true,
        "question_id": 30595187,
        "item_type": "question",
        "score": 12,
        "last_activity_date": 1468405743,
        "creation_date": 1433245540,
        "body": "Hello dear stackoverflower,\n\nIn my project, i am using the new &quot;android design library&quot;.\nThe problem is, that there is a runtime exception which says(Im trying to create a FloatingButton):\n\n\n\nI was able to figure out, which the attribute cannot be resolved :\n\n\n\nThis is located in res/values/styles/styles.xml in the android-design-library\n\ni have read in this post that the API lvl should bis 21+. But as the design library supports API 7+, this should not be a problem actually.\n\nIt is also worth to mention that i have not included the design library as a gradle-dependency like this:\n\n\n\nI am adding the library manually to the project because the Jenkins server has no Internet access.\nI have updated the support-v4 library to 21.2.0\nalso the appcompat support-v7 is included and updated.\n\nHere is the android-design-library gradle file:\n\n\n\nIt would be great if someone can help me.\n",
        "excerpt": "Hello dear stackoverflower,\n\nIn my project, i am using the new &quot;android design library&quot;.\nThe problem is, that there is a runtime exception which says(Im trying to create a FloatingButton):\n\n java.lang &hellip; ",
        "title": "Android XML: RuntimeException: Failed to resolve attribute at index 6"
    }, {
        "tags": ["solr", "typo3", "typo3-7.6.x"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 38348879,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468405520,
        "creation_date": 1468405123,
        "body": "I have written the index configurations for my custome module in typo3 7.6.4 but while indexing content, solr search extension throwing RuntimeException error for pages. when i check the error it shows same error for all the pages.\n\n\n  1331837081: exception &#39;RuntimeException&#39; with message &#39;Failed indexing page Index Queue item 1470&#39; in /typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php:388\n  \n  Stack trace:\n  #0 /typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(71): ApacheSolrForTypo3\\Solr\\IndexQueue\\PageIndexer-&gt;indexPage(Object(ApacheSolrForTypo3\\Solr\\IndexQueue\\Item), 0, &#39;0&#39;)\n  #1 /typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(158):\n\n",
        "excerpt": "I have written the index configurations for my custome module in typo3 7.6.4 but while indexing content, solr search extension throwing <span class=\"highlight\">RuntimeException</span> error for pages. when i check the error &hellip;  it shows same error for all the pages.\n\n\n  1331837081: exception &#39;<span class=\"highlight\">RuntimeException</span>&#39; with message &#39;Failed indexing page Index Queue item 1470&#39; in /typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php:388 &hellip; ",
        "title": "Keep getting RuntimeException error while indexing pages in solr search in typo3"
    }, {
        "tags": ["selenium", "selenium-webdriver", "testng"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 0,
        "is_answered": false,
        "question_id": 37785491,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1465809196,
        "creation_date": 1465808218,
        "body": "I am facing problems in getting the screenshots appear in the test report.\n\nBelow is the code which I am using to capture screenshots and append it to the report\n\n\n\nThe screen are being captured. It&#39;s even getting appended in the report as shown below:\n\n\r\n\r\n\r\n\r\n\r\n\n\nWhen I open the report, I don&#39;t see the image. But when open the source of the page and click on the img src, the file opens.\n\nWhat am i doing wrong? Why is the image not shown in the report.\n\nAny help appreciated.\n",
        "excerpt": "(&quot;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ &quot;);\n        logger.debug(&quot;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <span class=\"highlight\">Fail</span> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ &quot; + tr.getName());\n        logger.debug &hellip; &quot;+fileName+&quot;\\&quot; height=&#39;100&#39; width=&#39;100&#39;&gt;Screenshot&lt;/a&gt;&quot;);\n            Reporter.setCurrentTestResult(null);\n\n        } catch (IOException e) {\n            logger.debug(e, new <span class=\"highlight\">RuntimeException</span> &hellip; ",
        "title": "Problems with appending screenshot to the Testng report"
    }],
    "name": "RuntimeException fail"
}, {
    "items": [{
        "tags": ["java", "spring", "maven", "jpa", "aspectj"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38200747,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468670040,
        "creation_date": 1467713576,
        "body": "I am trying aspectj with EntityManager, its giving error\n\n\n\nPOM:    \n\n\n\nDriver application:\n\n\n\nService class:\n\n\n\nAspect:\n\n\n\napplication.properties:\n\n\n\nNeed to know where am doing wrong??\n",
        "excerpt": "&gt;\n        &lt;dependency&gt;\n            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n            &lt;artifactId&gt;spring-boot-starter-<span class=\"highlight\">test</span>&lt;/artifactId&gt;\n            &lt;scope&gt;<span class=\"highlight\">test</span>&lt;/scope&gt;\n        &lt;/dependency&gt;\n\n    &lt;/dependencies &hellip; );\n            service.save();\n\n        } catch (<span class=\"highlight\">RuntimeException</span> e) {\n            System.out.println(&quot;Caught runtime exception&quot;);\n        }\n    }\n}\n\n\nService class:\n\n@Component\npublic class Service &hellip; ",
        "title": "EntityManager with aspectj is not working"
    }, {
        "tags": ["java", "neo4j", "cypher", "spring-data-neo4j"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38403130,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468636713,
        "creation_date": 1468608170,
        "body": "I have uploaded a CSV file and already have nodes and relationship defined on Neo4j. I&#39;ve tried to create a program base on an example that basically run a cypher query from Spring that would generate the output from neo4j. However, I&#39;m encountering this error:\n\n\n\nI&#39;m wondering what could possibly be the error? \nHere is my code:\n\n\n\n}\n",
        "excerpt": "){\n    Neo4j <span class=\"highlight\">test</span> = new Neo4j();\n    test.run();\n}\nvoid run()\n{   \n\n    clear();\n    GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(DB_PATH);\n\n    try(Transaction tx1 &hellip; )-[:APPLIES_TO]-&gt;(e:Time) RETURN b,e&quot;).resultAsString();\n    }\n\n    db.shutdown();\n    }\n}\n\nprivate void clear(){\n    try{\n        deleteRecursively(DB_PATH);\n    }\n    catch(IOException e){\n        throw new <span class=\"highlight\">RuntimeException</span>(e);\n    }\n}\n\n\n}\n &hellip; ",
        "title": "Run a Cypher query from Spring to Neo4j"
    }, {
        "tags": ["java", "code-coverage", "bytecode", "jacoco", "try-with-resources"],
        "question_score": 35,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 4,
        "is_answered": true,
        "question_id": 17354150,
        "item_type": "question",
        "score": 35,
        "last_activity_date": 1467929771,
        "creation_date": 1372371365,
        "body": "I&#39;ve got some code that uses try with resources and in jacoco it&#39;s coming up as only half covered. All the source code lines are green, but I get a little yellow symbol telling me that only 4 of 8 branches are covered.\n\n\n\nI&#39;m having trouble figuring out what all the branches are, and how to write code that covers them. Three possible places throw . These are ,  and the implied \n\n\nNot throwing any exceptions, \nthrowing an exception from \nthrowing an exception from \nthrowing an exception from \nthrowing an exception from  and \n\n\nI can&#39;t think of any other cases, yet I still only have 4 of 8 covered.\n\nCan someone explain to me why it&#39;s 4 of 8 and is there anyway to hit all 8 branches? I&#39;m not skilled with decyrpting/reading/interpreting byte code, but maybe you are... :) I&#39;ve already seen https://github.com/jacoco/jacoco/issues/82, but neither it nor the issue it references help very much (other than noting that this is due to compiler generated blocks)\n\nHmm, just as I finish writing this I had a thought on what case(s) might not be not tested by what I mention above... I&#39;ll post an answer if I got it right. I&#39;m sure this question and it&#39;s answer will help someone in any case.\n\nEDIT: Nope, I didn&#39;t find it. Throwing RuntimeExceptions (not handled by the catch block) didn&#39;t cover any more branches\n",
        "excerpt": "I&#39;ve got some code that uses try with resources and in jacoco it&#39;s coming up as only half covered. All the source code lines are green, but I get a little yellow symbol telling me that only 4 of 8 bra &hellip; ",
        "title": "8 branches for try with resources - jacoco coverage possible?"
    }, {
        "tags": ["java"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 38253081,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1467918554,
        "creation_date": 1467917069,
        "body": "code 1:\n\n\n\no/p for code1:-Radial Tire with int\n\ncode 2:-\n\n\n\no/p for code2:- Radial Tire with long\n\nWhy in code1 child class int method is called while in code2 parent class long method is called? If this occurs due to widening then why in case1 widening does not take place? In code1 why a child class int method is called when an int method already exist in parent class?\n",
        "excerpt": "code 1:\n\nclass Tyre \n{\n    public void front() throws <span class=\"highlight\">RuntimeException</span> \n    {\n        System.out.println(&quot;Tire&quot;);\n    }\n    public void front(int a) \n    {\n        System.out.println(&quot;Radial Tire &hellip; () \n{\n        System.out.println(&quot;Radial Tire&quot;);\n    }\n    public void front(int a) \n    {\n        System.out.println(&quot;Radial Tire with int&quot;);\n    }\n}\n\nclass <span class=\"highlight\">Test</span>\n{\n      public static void main(String... args &hellip; ",
        "title": "Overriding- Why long is called instead of int"
    }, {
        "tags": ["java", "multithreading", "exception-handling"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38239176,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1467900678,
        "creation_date": 1467874441,
        "body": "I am working on a Uni project to implement a Texas Hold&#39;em poker game. I have been working on a way to to halt the game while waiting for user input (from GUI) if no input is received then the player will be folded. \nMy initial code just called  on the game thread and then  from the controller. The problem I ran into with this method was I had no way to tell if the controller had notified or the that sleep had ended. \nTo try and flag this I had the controller throw a  but have had alot of trouble trying to catch this exception at the game thread.\n\nHere is my minimum viable example: \n\nGUI.java\n\n\n\nTestController.java\n\n\n\nWaitTest.java\n\n\n\nDriver.java\n\n\n\nThe runtime Exception is never caught is there a simple way to catch this? or is there a better way to stop the game loop and wait for input? This is my first attempt at thread control/concurrency so I am probably overlooking something simple\n",
        "excerpt": " notified or the that sleep had ended. \nTo try and flag this I had the controller throw a <span class=\"highlight\">RuntimeException</span> but have had alot of trouble trying to catch this exception at the game thread.\n\nHere is my &hellip;  method stub\n        System.out.println(&quot;Controller throws runtime&quot;);\n        synchronized(wt.getT())\n        {\n            throw new <span class=\"highlight\">RuntimeException</span>(&quot;Runtime flying&quot;);\n        }\n    }\n}\n\n\nWaitTest.java &hellip; ",
        "title": "Catch a Runtime Exception thrown from ActionListener in a Waiting Runnable"
    }, {
        "tags": ["java", "openid", "openid-connect"],
        "question_score": 2,
        "is_accepted": true,
        "answer_id": 25041502,
        "is_answered": false,
        "question_id": 24875253,
        "item_type": "answer",
        "score": 3,
        "last_activity_date": 1467724315,
        "creation_date": 1406735886,
        "body": "The following example will validate an  from an OAuth2 call for Salesforce, without any 3rd party libraries. Note that you&#39;ll have to supply a valid  below to test this out. \n\n\n\nNote if you&#39;re not opposed to using a third party library, I&#39;d totally suggest using this, as it works great. I couldn&#39;t use it for business reasons, but was glad to find it as it helped me understand how this process works, validated an , I&#39;m sure in a much more robust way.\n\nAlso, to be certain this request was signed by the same client, ensure the  parameter in the payload matches your own client key given to you by Salesforce.\n",
        "excerpt": "The following example will validate an id_token from an OAuth2 call for Salesforce, without any 3rd party libraries. Note that you&#39;ll have to supply a valid id_token below to <span class=\"highlight\">test</span> this out. \n\npackage &hellip;  that needs validation. This is probably the only field you need to change to <span class=\"highlight\">test</span> your id_token.\n    // If it doesn&#39;t work, try making sure the MODULUS and EXPONENT constants are what you&#39;re using &hellip; ",
        "title": "OpenID Connect - how to verify id token in Java?"
    }],
    "name": "RuntimeException test"
}, {
    "items": [{
        "tags": ["java", "spring", "maven", "jpa", "aspectj"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": true,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38200747,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468670040,
        "creation_date": 1467713576,
        "body": "I am trying aspectj with EntityManager, its giving error\n\n\n\nPOM:    \n\n\n\nDriver application:\n\n\n\nService class:\n\n\n\nAspect:\n\n\n\napplication.properties:\n\n\n\nNeed to know where am doing wrong??\n",
        "excerpt": ");\n            service.save();\n\n        } catch (<span class=\"highlight\">RuntimeException</span> e) {\n            System.out.println(&quot;Caught runtime <span class=\"highlight\">exception</span>&quot;);\n        }\n    }\n}\n\n\nService class:\n\n@Component\npublic class Service &hellip; &gt;\n        &lt;dependency&gt;\n            &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;\n            &lt;artifactId&gt;spring-boot-starter-<span class=\"highlight\">test</span>&lt;/artifactId&gt;\n            &lt;scope&gt;<span class=\"highlight\">test</span>&lt;/scope&gt;\n        &lt;/dependency&gt;\n\n    &lt;/dependencies &hellip; ",
        "title": "EntityManager with aspectj is not working"
    }, {
        "tags": ["java", "neo4j", "cypher", "spring-data-neo4j"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": false,
        "question_id": 38403130,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468636713,
        "creation_date": 1468608170,
        "body": "I have uploaded a CSV file and already have nodes and relationship defined on Neo4j. I&#39;ve tried to create a program base on an example that basically run a cypher query from Spring that would generate the output from neo4j. However, I&#39;m encountering this error:\n\n\n\nI&#39;m wondering what could possibly be the error? \nHere is my code:\n\n\n\n}\n",
        "excerpt": " generate the output from neo4j. However, I&#39;m encountering this error:\n\n<span class=\"highlight\">Exception</span> in thread &quot;main&quot; java.lang.NoSuchMethodError:org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(Ljava/io/File &hellip; ){\n    Neo4j <span class=\"highlight\">test</span> = new Neo4j();\n    test.run();\n}\nvoid run()\n{   \n\n    clear();\n    GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(DB_PATH);\n\n    try(Transaction tx1 &hellip; ",
        "title": "Run a Cypher query from Spring to Neo4j"
    }, {
        "tags": ["java", "design-patterns", "initializer"],
        "question_score": 0,
        "is_accepted": false,
        "has_accepted_answer": false,
        "answer_count": 1,
        "is_answered": true,
        "question_id": 38378600,
        "item_type": "question",
        "score": 0,
        "last_activity_date": 1468594464,
        "creation_date": 1468510892,
        "body": "to avoid the overridable method call in constructor dilemma this approache delegate the variables initialization and calls to overridable methods to a member method that return reference to the instance its self and exception to be thrown if trying to use instance without invoking the initialization method/s so that the creation of objects will look like this \n\n\n\nmy super class should implement methods of initializable interface it has two methods\n\n1) initialize method in which i write code to do the following in order \n\na) call setter methods and other initialization code\nb) make call to overridable method putting them at end of the method\nthis method can be overloaded to provide versions of it with necessary arguments as illustrated in complex example  \n\n2) isInitialzed method to check if the initialization done or not when a call to a method in my class that reference a variable that is initialized in initialize method and initialization not done i throw my NonInitializedInstanceException \n\nthe subclass should override the initialize method/s &quot;all the super class versions of the initialize method&quot; and do the following in order \n\n1)initialize its variables\n2)can call super method that don&#39;t throw NonInitializedInstanceException\n3)call super.initialize() method\n4)call setter methods &quot;note that the super call the setters so to avoid our setter been useless we should call it after super initialize method call&quot;\n5)can call super method that throw NonInitializedInstanceException\n\nhandling overloaded versions of initialize done by calling the one with more parameters from the less parameter one  \n\nthe following are my code \n\nthe interface\n\n\n\nthe NonInitializedInstanceException  class\n\n\n\nexample of using them\n\n\n\na more complicated example using initializer with arguments\n\n\n\nsuggestion of using static method factory pattern and as i expected static pain never ends here is my trial to adapt my pattern into static one but i failed i don&#39;t know how to make subClass invoke superClass create method to affect its instance  \n\n\n\ni hope it be a good idea waiting for your comments and suggestions\n",
        "excerpt": " interface\n * you can <span class=\"highlight\">test</span> if initialization was done or not by isInialized method \n * of the same interface if false throw the <span class=\"highlight\">exception</span> \n */\npublic class NonInitializedInstanceException extends &hellip;  to the instance its self and <span class=\"highlight\">exception</span> to be thrown if trying to use instance without invoking the initialization method/s so that the creation of objects will look like this \n\n    SuperClass sup = new SuperClass &hellip; ",
        "title": "java member method initializer pattern to what extent this design is correct bug safe and suggestions to improve it"
    }],
    "name": "RuntimeException test exception"
}, {
    "items": [{
        "tags": ["java", "jpa", "cdi", "entitymanager", "java-ee-7"],
        "question_score": 11,
        "is_accepted": false,
        "answer_id": 30007786,
        "is_answered": false,
        "question_id": 19431423,
        "item_type": "answer",
        "score": 8,
        "last_activity_date": 1464320225,
        "creation_date": 1430602742,
        "body": "You&#39;re almost right on with your CDI producer. Only thing is that you should use a producer method instead of a producer field.\n\nIf you&#39;re using Weld as CDI container (GlassFish 4.1 and WildFly 8.2.0), then your example of combining ,  and  on a producer field should throw this exception during deployment:\n\n\n  org.jboss.weld.exceptions.DefinitionException: WELD-001502:\n  Resource producer field [Resource Producer Field [EntityManager] with\n  qualifiers [@Any @Default] declared as [[BackedAnnotatedField]\n  @Produces @RequestScoped @PersistenceContext\n  com.somepackage.EntityManagerProducer.entityManager]] must be\n  @Dependent scoped\n\n\nTurns out that the container is not required to support any other scope than @Dependent when using a producer field to lookup Java EE resources.\n\nCDI 1.2, section 3.7. Resources:\n\n\n  The container is not required to support resources with scope other\n  than @Dependent. Portable applications should not define resources\n  with any scope other than @Dependent.\n\n\nThis quote was all about producer fields. Using a producer method to lookup a resource is totally legit:\n\n\n\nFirst, the container will instantiate the producer and a container-managed entity manager reference will be injected into the  field. Then the container will call your producer method and wrap what he returns in a request scoped CDI proxy. This CDI proxy is what your client code get when using . Because the producer class is @Dependent (default), the underlying container-managed entity manager reference will not be shared by any other CDI proxies produced. Every time another request want the entity manager, a new instance of the producer class will be instantiated and a new entity manager reference will be injected into the producer which in turn is wrapped in a new CDI proxy.\n\nTo be technically correct, the underlying and unnamed container who do the resource injection into the field  is allowed to reuse old entity managers (see footnote in JPA 2.1 specification, section &quot;7.9.1 Container Responsibilities&quot;, page 357). But so far, we honor the programming model required by JPA.\n\nIn the preceding example, it would not matter if you mark  @Dependent or @RequestScoped. Using @Dependent is semantically more correct. But if you put a wider scope than request scope on the producer class you risk exposing the underlying entity manager reference to many threads which we both know is not a good thing to do. The underlying entity manager implementation is probably a thread-local object, but portable applications cannot rely on implementation details.\n\nCDI does not know how to close whatever stuff it is that you put into the request bound context. More so than anything else, a container-managed entity manager must not be closed by application code.\n\nJPA 2.1, section &quot;7.9.1 Container Responsibilities&quot;:\n\n\n  The container must throw the IllegalStateException if the application\n  calls EntityManager.close on a container-managed entity manager.\n\n\nUnfortunately, many people do use a  method to close the container-managed entity manager. Who can blame them when the official Java EE 7 tutorial provided by Oracle as well as the CDI specification itself use a disposer to close a container-managed entity manager. This is simply wrong and the call to  will throw a  no matter where you put that call, in a disposer method or somewhere else. The Oracle example is the biggest sinner of the two by declaring the producer class to be a . As we learned, this risk exposing the underlying entity manager reference to many different threads.\n\nIt has been proven here that by using CDI producers and disposers wrongfully, 1) the not thread-safe entity manager may be leaked to many threads and 2) the disposer has no effect; leaving the entity manager open. What happened was the IllegalStateException which the container swallowed leaving no trace of it (a mysterious log entry is made which says there was an &quot;error destroying an instance&quot;).\n\nGenerally, using CDI to lookup container-managed entity managers is not a good idea. The application is most likely better off just using  and be happy with it. But there are always exceptions to the rule like in your example, and CDI can also be useful to abstract away the  when handling the life cycle of application-managed entity managers.\n\nTo get a complete picture on how to obtain a container-managed entity manager and how to use CDI to lookup entity managers, you might want to read this and this.\n",
        "excerpt": " not matter if you mark EntityManagerProducer @Dependent or @RequestScoped. Using @Dependent is semantically <span class=\"highlight\">more</span> correct. But if you put a wider scope <span class=\"highlight\">than</span> <span class=\"highlight\">request</span> scope on the producer class you risk &hellip; , but portable applications cannot rely on implementation details.\n\nCDI does not know how to close whatever stuff it is that you put into the <span class=\"highlight\">request</span> bound context. <span class=\"highlight\">More</span> so <span class=\"highlight\">than</span> anything else, a container-managed &hellip; ",
        "title": "Getting a reference to EntityManager in Java EE applications using CDI"
    }]}];
